// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1169 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1169() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "glfwSetWindowPosCallback",
        constants$142.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glfwSetWindowSizeCallback",
        constants$142.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glfwSetWindowCloseCallback",
        constants$142.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "glfwSetWindowRefreshCallback",
        constants$142.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glfwSetWindowFocusCallback",
        constants$142.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glfwSetWindowIconifyCallback",
        constants$142.const$4
    );
}


