// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$350 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$350() {}
    static final VarHandle const$0 = constants$347.const$2.varHandle(MemoryLayout.PathElement.groupElement("shaderIntegerDotProduct"));
    static final VarHandle const$1 = constants$347.const$2.varHandle(MemoryLayout.PathElement.groupElement("maintenance4"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("minSubgroupSize"),
        JAVA_INT.withName("maxSubgroupSize"),
        JAVA_INT.withName("maxComputeWorkgroupSubgroups"),
        JAVA_INT.withName("requiredSubgroupSizeStages"),
        JAVA_INT.withName("maxInlineUniformBlockSize"),
        JAVA_INT.withName("maxPerStageDescriptorInlineUniformBlocks"),
        JAVA_INT.withName("maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks"),
        JAVA_INT.withName("maxDescriptorSetInlineUniformBlocks"),
        JAVA_INT.withName("maxDescriptorSetUpdateAfterBindInlineUniformBlocks"),
        JAVA_INT.withName("maxInlineUniformTotalSize"),
        JAVA_INT.withName("integerDotProduct8BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProduct8BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProduct8BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProduct4x8BitPackedUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProduct4x8BitPackedSignedAccelerated"),
        JAVA_INT.withName("integerDotProduct4x8BitPackedMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProduct16BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProduct16BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProduct16BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProduct32BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProduct32BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProduct32BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProduct64BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProduct64BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProduct64BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating8BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating8BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating16BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating16BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating32BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating32BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating64BitUnsignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating64BitSignedAccelerated"),
        JAVA_INT.withName("integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated"),
        JAVA_LONG.withName("storageTexelBufferOffsetAlignmentBytes"),
        JAVA_INT.withName("storageTexelBufferOffsetSingleTexelAlignment"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("uniformTexelBufferOffsetAlignmentBytes"),
        JAVA_INT.withName("uniformTexelBufferOffsetSingleTexelAlignment"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("maxBufferSize")
    ).withName("VkPhysicalDeviceVulkan13Properties");
    static final VarHandle const$3 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$4 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$5 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("minSubgroupSize"));
}


