// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$809 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$809() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PFN_vkCmdSetDepthCompareOpEXT.class, "apply", constants$178.const$3);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkCmdSetDepthBoundsTestEnableEXT.class, "apply", constants$178.const$3);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(PFN_vkCmdSetStencilTestEnableEXT.class, "apply", constants$178.const$3);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkCmdSetStencilOpEXT.class, "apply", constants$168.const$0);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkCmdSetCullModeEXT",
        constants$178.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCmdSetFrontFaceEXT",
        constants$178.const$3
    );
}


