// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$821 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$821() {}
    static final VarHandle const$0 = constants$820.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$820.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$820.const$5.varHandle(MemoryLayout.PathElement.groupElement("swapchain"));
    static final VarHandle const$3 = constants$820.const$5.varHandle(MemoryLayout.PathElement.groupElement("imageIndexCount"));
    static final VarHandle const$4 = constants$820.const$5.varHandle(MemoryLayout.PathElement.groupElement("pImageIndices"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_vkReleaseSwapchainImagesEXT.class, "apply", constants$144.const$2);
}


