// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$424 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$424() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkCmdCopyImage2",
        constants$14.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCmdCopyBufferToImage2",
        constants$14.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkCmdCopyImageToBuffer2",
        constants$14.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkCmdBlitImage2",
        constants$14.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkCmdResolveImage2",
        constants$14.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCmdBeginRendering",
        constants$14.const$0
    );
}


