// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$912 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$912() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PFN_vkCmdSetVertexInputEXT.class, "apply", constants$159.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCmdSetVertexInputEXT",
        constants$159.const$4
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("hasPrimary"),
        JAVA_INT.withName("hasRender"),
        JAVA_LONG.withName("primaryMajor"),
        JAVA_LONG.withName("primaryMinor"),
        JAVA_LONG.withName("renderMajor"),
        JAVA_LONG.withName("renderMinor")
    ).withName("VkPhysicalDeviceDrmPropertiesEXT");
    static final VarHandle const$3 = constants$912.const$2.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$4 = constants$912.const$2.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$5 = constants$912.const$2.varHandle(MemoryLayout.PathElement.groupElement("hasPrimary"));
}


