// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$441 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$441() {}
    static final VarHandle const$0 = constants$440.const$4.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$1 = constants$440.const$4.varHandle(MemoryLayout.PathElement.groupElement("modes"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(PFN_vkCreateSwapchainKHR.class, "apply", constants$143.const$2);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkDestroySwapchainKHR.class, "apply", constants$142.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(PFN_vkGetSwapchainImagesKHR.class, "apply", constants$143.const$2);
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


