// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$600 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$600() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$599.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkGetQueueCheckpointData2NV.class, "apply", constants$142.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkCmdSetEvent2KHR",
        constants$142.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkCmdResetEvent2KHR",
        constants$169.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkCmdWaitEvents2KHR",
        constants$416.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCmdPipelineBarrier2KHR",
        constants$14.const$0
    );
}


