// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$973 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$973() {}
    static final VarHandle const$0 = constants$972.const$4.varHandle(MemoryLayout.PathElement.groupElement("dstAddress"));
    static final VarHandle const$1 = constants$972.const$4.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("srcAddress"),
        JAVA_INT.withName("bufferRowLength"),
        JAVA_INT.withName("bufferImageHeight"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("aspectMask"),
            JAVA_INT.withName("mipLevel"),
            JAVA_INT.withName("baseArrayLayer"),
            JAVA_INT.withName("layerCount")
        ).withName("imageSubresource"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("z")
        ).withName("imageOffset"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("depth")
        ).withName("imageExtent")
    ).withName("VkCopyMemoryToImageIndirectCommandNV");
    static final VarHandle const$3 = constants$973.const$2.varHandle(MemoryLayout.PathElement.groupElement("srcAddress"));
    static final VarHandle const$4 = constants$973.const$2.varHandle(MemoryLayout.PathElement.groupElement("bufferRowLength"));
    static final VarHandle const$5 = constants$973.const$2.varHandle(MemoryLayout.PathElement.groupElement("bufferImageHeight"));
}


