// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$555 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$555() {}
    static final VarHandle const$0 = constants$552.const$0.varHandle(MemoryLayout.PathElement.groupElement("pcm_sample_bit_depth_luma_minus1"));
    static final VarHandle const$1 = constants$552.const$0.varHandle(MemoryLayout.PathElement.groupElement("pcm_sample_bit_depth_chroma_minus1"));
    static final VarHandle const$2 = constants$552.const$0.varHandle(MemoryLayout.PathElement.groupElement("log2_min_pcm_luma_coding_block_size_minus3"));
    static final VarHandle const$3 = constants$552.const$0.varHandle(MemoryLayout.PathElement.groupElement("log2_diff_max_min_pcm_luma_coding_block_size"));
    static final VarHandle const$4 = constants$552.const$0.varHandle(MemoryLayout.PathElement.groupElement("reserved1"));
    static final VarHandle const$5 = constants$552.const$0.varHandle(MemoryLayout.PathElement.groupElement("reserved2"));
}


