// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$353 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$353() {}
    static final VarHandle const$0 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct4x8BitPackedUnsignedAccelerated"));
    static final VarHandle const$1 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct4x8BitPackedSignedAccelerated"));
    static final VarHandle const$2 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct4x8BitPackedMixedSignednessAccelerated"));
    static final VarHandle const$3 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct16BitUnsignedAccelerated"));
    static final VarHandle const$4 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct16BitSignedAccelerated"));
    static final VarHandle const$5 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct16BitMixedSignednessAccelerated"));
}


