// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$839 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$839() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkCmdExecuteGeneratedCommandsNV",
        constants$140.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCmdBindPipelineShaderGroupNV",
        constants$176.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkCreateIndirectCommandsLayoutNV",
        constants$143.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkDestroyIndirectCommandsLayoutNV",
        constants$142.const$0
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("inheritedViewportScissor2D"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDeviceInheritedViewportScissorFeaturesNV");
    static final VarHandle const$5 = constants$839.const$4.varHandle(MemoryLayout.PathElement.groupElement("sType"));
}


