// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$723 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$723() {}
    static final VarHandle const$0 = constants$721.const$0.varHandle(MemoryLayout.PathElement.groupElement("transformData"));
    static final VarHandle const$1 = constants$721.const$0.varHandle(MemoryLayout.PathElement.groupElement("transformOffset"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        RuntimeHelper.POINTER.withName("aabbData"),
        JAVA_INT.withName("numAABBs"),
        JAVA_INT.withName("stride"),
        JAVA_LONG.withName("offset")
    ).withName("VkGeometryAABBNV");
    static final VarHandle const$3 = constants$723.const$2.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$4 = constants$723.const$2.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$5 = constants$723.const$2.varHandle(MemoryLayout.PathElement.groupElement("aabbData"));
}


