// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1113 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1113() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "glLineWidth",
        constants$1085.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glListBase",
        constants$1082.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glLoadIdentity",
        constants$0.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "glLoadMatrixd",
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glLoadMatrixf",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glLoadName",
        constants$1082.const$5
    );
}


