// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$146 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$146() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkQueueWaitIdle.class, "apply", constants$146.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$146.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkDeviceWaitIdle.class, "apply", constants$146.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(PFN_vkAllocateMemory.class, "apply", constants$143.const$2);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_vkFreeMemory.class, "apply", constants$142.const$0);
}


