// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$380 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$380() {}
    static final VarHandle const$0 = constants$379.const$4.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$1 = constants$379.const$4.varHandle(MemoryLayout.PathElement.groupElement("srcImage"));
    static final VarHandle const$2 = constants$379.const$4.varHandle(MemoryLayout.PathElement.groupElement("srcImageLayout"));
    static final VarHandle const$3 = constants$379.const$4.varHandle(MemoryLayout.PathElement.groupElement("dstImage"));
    static final VarHandle const$4 = constants$379.const$4.varHandle(MemoryLayout.PathElement.groupElement("dstImageLayout"));
    static final VarHandle const$5 = constants$379.const$4.varHandle(MemoryLayout.PathElement.groupElement("regionCount"));
}


