// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1007 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1007() {}
    static final VarHandle const$0 = constants$1006.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$1006.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$1006.const$5.varHandle(MemoryLayout.PathElement.groupElement("mode"));
    static final VarHandle const$3 = constants$1006.const$5.varHandle(MemoryLayout.PathElement.groupElement("driverCount"));
    static final VarHandle const$4 = constants$1006.const$5.varHandle(MemoryLayout.PathElement.groupElement("pDrivers"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("shaderModuleIdentifier"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT");
}


