// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$367 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$367() {}
    static final VarHandle const$0 = constants$365.const$4.varHandle(MemoryLayout.PathElement.groupElement("dstQueueFamilyIndex"));
    static final VarHandle const$1 = constants$365.const$4.varHandle(MemoryLayout.PathElement.groupElement("buffer"));
    static final VarHandle const$2 = constants$365.const$4.varHandle(MemoryLayout.PathElement.groupElement("offset"));
    static final VarHandle const$3 = constants$365.const$4.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_LONG.withName("srcStageMask"),
        JAVA_LONG.withName("srcAccessMask"),
        JAVA_LONG.withName("dstStageMask"),
        JAVA_LONG.withName("dstAccessMask"),
        JAVA_INT.withName("oldLayout"),
        JAVA_INT.withName("newLayout"),
        JAVA_INT.withName("srcQueueFamilyIndex"),
        JAVA_INT.withName("dstQueueFamilyIndex"),
        RuntimeHelper.POINTER.withName("image"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("aspectMask"),
            JAVA_INT.withName("baseMipLevel"),
            JAVA_INT.withName("levelCount"),
            JAVA_INT.withName("baseArrayLayer"),
            JAVA_INT.withName("layerCount")
        ).withName("subresourceRange"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkImageMemoryBarrier2");
    static final VarHandle const$5 = constants$367.const$4.varHandle(MemoryLayout.PathElement.groupElement("sType"));
}


