// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1103() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "glGetBooleanv",
        constants$1086.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glGetClipPlane",
        constants$1086.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glGetDoublev",
        constants$1086.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glGetError",
        constants$1103.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glGetFloatv",
        constants$1086.const$0
    );
}


