// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$887 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$887() {}
    static final VarHandle const$0 = constants$886.const$0.varHandle(MemoryLayout.PathElement.groupElement("c"));
    static final VarHandle const$1 = constants$886.const$0.varHandle(MemoryLayout.PathElement.groupElement("pvy"));
    static final VarHandle const$2 = constants$886.const$0.varHandle(MemoryLayout.PathElement.groupElement("sz"));
    static final VarHandle const$3 = constants$886.const$0.varHandle(MemoryLayout.PathElement.groupElement("pvz"));
    static final VarHandle const$4 = constants$886.const$0.varHandle(MemoryLayout.PathElement.groupElement("qx"));
    static final VarHandle const$5 = constants$886.const$0.varHandle(MemoryLayout.PathElement.groupElement("qy"));
}


