// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final VarHandle const$0 = constants$31.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxImageDimension1D"));
    static final VarHandle const$1 = constants$31.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxImageDimension2D"));
    static final VarHandle const$2 = constants$31.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxImageDimension3D"));
    static final VarHandle const$3 = constants$31.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxImageDimensionCube"));
    static final VarHandle const$4 = constants$31.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxImageArrayLayers"));
    static final VarHandle const$5 = constants$31.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxTexelBufferElements"));
}


