// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$405 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$405() {}
    static final VarHandle const$0 = constants$403.const$4.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct4x8BitPackedMixedSignednessAccelerated"));
    static final VarHandle const$1 = constants$403.const$4.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct16BitUnsignedAccelerated"));
    static final VarHandle const$2 = constants$403.const$4.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct16BitSignedAccelerated"));
    static final VarHandle const$3 = constants$403.const$4.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct16BitMixedSignednessAccelerated"));
    static final VarHandle const$4 = constants$403.const$4.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct32BitUnsignedAccelerated"));
    static final VarHandle const$5 = constants$403.const$4.varHandle(MemoryLayout.PathElement.groupElement("integerDotProduct32BitSignedAccelerated"));
}


