// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1168 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1168() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glfwSetWindowMonitor",
        constants$1168.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glfwGetWindowAttrib",
        constants$162.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "glfwSetWindowAttrib",
        constants$165.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glfwSetWindowUserPointer",
        constants$14.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glfwGetWindowUserPointer",
        constants$1159.const$5
    );
}


