// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1022 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1022() {}
    static final VarHandle const$0 = constants$1021.const$3.varHandle(MemoryLayout.PathElement.groupElement("legacyDithering"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("pipelineProtectedAccess"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDevicePipelineProtectedAccessFeaturesEXT");
    static final VarHandle const$2 = constants$1022.const$1.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$3 = constants$1022.const$1.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$4 = constants$1022.const$1.varHandle(MemoryLayout.PathElement.groupElement("pipelineProtectedAccess"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("shaderObject"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDeviceShaderObjectFeaturesEXT");
}


