// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1010 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1010() {}
    static final VarHandle const$0 = constants$1009.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$1009.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$1009.const$5.varHandle(MemoryLayout.PathElement.groupElement("identifierSize"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkGetShaderModuleIdentifierEXT.class, "apply", constants$142.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(PFN_vkGetShaderModuleCreateInfoIdentifierEXT.class, "apply", constants$142.const$0);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkGetShaderModuleIdentifierEXT",
        constants$142.const$0
    );
}


