// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$543 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$543() {}
    static final VarHandle const$0 = constants$542.const$3.varHandle(MemoryLayout.PathElement.groupElement("reserved1"));
    static final VarHandle const$1 = constants$542.const$3.varHandle(MemoryLayout.PathElement.groupElement("reserved2"));
    static final VarHandle const$2 = constants$542.const$3.varHandle(MemoryLayout.PathElement.groupElement("vps_num_units_in_tick"));
    static final VarHandle const$3 = constants$542.const$3.varHandle(MemoryLayout.PathElement.groupElement("vps_time_scale"));
    static final VarHandle const$4 = constants$542.const$3.varHandle(MemoryLayout.PathElement.groupElement("vps_num_ticks_poc_diff_one_minus1"));
    static final VarHandle const$5 = constants$542.const$3.varHandle(MemoryLayout.PathElement.groupElement("reserved3"));
}


