// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$191 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$191() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkDestroyPipelineLayout",
        constants$142.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCreateSampler",
        constants$143.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkDestroySampler",
        constants$142.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkCreateDescriptorSetLayout",
        constants$143.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkDestroyDescriptorSetLayout",
        constants$142.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCreateDescriptorPool",
        constants$143.const$2
    );
}


