// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final VarHandle const$0 = constants$99.const$3.varHandle(MemoryLayout.PathElement.groupElement("dstColorBlendFactor"));
    static final VarHandle const$1 = constants$99.const$3.varHandle(MemoryLayout.PathElement.groupElement("colorBlendOp"));
    static final VarHandle const$2 = constants$99.const$3.varHandle(MemoryLayout.PathElement.groupElement("srcAlphaBlendFactor"));
    static final VarHandle const$3 = constants$99.const$3.varHandle(MemoryLayout.PathElement.groupElement("dstAlphaBlendFactor"));
    static final VarHandle const$4 = constants$99.const$3.varHandle(MemoryLayout.PathElement.groupElement("alphaBlendOp"));
    static final VarHandle const$5 = constants$99.const$3.varHandle(MemoryLayout.PathElement.groupElement("colorWriteMask"));
}


