// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$777 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$777() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PFN_vkSetLocalDimmingAMD.class, "apply", constants$174.const$2);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkSetLocalDimmingAMD",
        constants$174.const$2
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("fragmentDensityMap"),
        JAVA_INT.withName("fragmentDensityMapDynamic"),
        JAVA_INT.withName("fragmentDensityMapNonSubsampledImages"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDeviceFragmentDensityMapFeaturesEXT");
    static final VarHandle const$3 = constants$777.const$2.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$4 = constants$777.const$2.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$5 = constants$777.const$2.varHandle(MemoryLayout.PathElement.groupElement("fragmentDensityMap"));
}


