// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1042 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1042() {}
    static final VarHandle const$0 = constants$1041.const$4.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$1 = constants$1041.const$4.varHandle(MemoryLayout.PathElement.groupElement("geometryType"));
    static final VarHandle const$2 = constants$1041.const$4.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("type"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("mode"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("srcAccelerationStructure"),
        RuntimeHelper.POINTER.withName("dstAccelerationStructure"),
        JAVA_INT.withName("geometryCount"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pGeometries"),
        RuntimeHelper.POINTER.withName("ppGeometries"),
        MemoryLayout.unionLayout(
            JAVA_LONG.withName("deviceAddress"),
            RuntimeHelper.POINTER.withName("hostAddress")
        ).withName("scratchData")
    ).withName("VkAccelerationStructureBuildGeometryInfoKHR");
    static final VarHandle const$4 = constants$1042.const$3.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$5 = constants$1042.const$3.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
}


