// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$297 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$297() {}
    static final VarHandle const$0 = constants$296.const$4.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$1 = constants$296.const$4.varHandle(MemoryLayout.PathElement.groupElement("srcSubpass"));
    static final VarHandle const$2 = constants$296.const$4.varHandle(MemoryLayout.PathElement.groupElement("dstSubpass"));
    static final VarHandle const$3 = constants$296.const$4.varHandle(MemoryLayout.PathElement.groupElement("srcStageMask"));
    static final VarHandle const$4 = constants$296.const$4.varHandle(MemoryLayout.PathElement.groupElement("dstStageMask"));
    static final VarHandle const$5 = constants$296.const$4.varHandle(MemoryLayout.PathElement.groupElement("srcAccessMask"));
}


