// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$832 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$832() {}
    static final VarHandle const$0 = constants$829.const$4.varHandle(MemoryLayout.PathElement.groupElement("pIndexTypes"));
    static final VarHandle const$1 = constants$829.const$4.varHandle(MemoryLayout.PathElement.groupElement("pIndexTypeValues"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("pipelineBindPoint"),
        JAVA_INT.withName("tokenCount"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pTokens"),
        JAVA_INT.withName("streamCount"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pStreamStrides")
    ).withName("VkIndirectCommandsLayoutCreateInfoNV");
    static final VarHandle const$3 = constants$832.const$2.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$4 = constants$832.const$2.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$5 = constants$832.const$2.varHandle(MemoryLayout.PathElement.groupElement("flags"));
}


