// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$653 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$653() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PFN_vkCmdBeginConditionalRenderingEXT.class, "apply", constants$14.const$0);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkCmdEndConditionalRenderingEXT.class, "apply", constants$0.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkCmdBeginConditionalRenderingEXT",
        constants$14.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkCmdEndConditionalRenderingEXT",
        constants$0.const$0
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("xcoeff"),
        JAVA_FLOAT.withName("ycoeff")
    ).withName("VkViewportWScalingNV");
    static final VarHandle const$5 = constants$653.const$4.varHandle(MemoryLayout.PathElement.groupElement("xcoeff"));
}


