// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$695 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$695() {}
    static final VarHandle const$0 = constants$694.const$4.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$1 = constants$694.const$4.varHandle(MemoryLayout.PathElement.groupElement("advancedBlendMaxColorAttachments"));
    static final VarHandle const$2 = constants$694.const$4.varHandle(MemoryLayout.PathElement.groupElement("advancedBlendIndependentBlend"));
    static final VarHandle const$3 = constants$694.const$4.varHandle(MemoryLayout.PathElement.groupElement("advancedBlendNonPremultipliedSrcColor"));
    static final VarHandle const$4 = constants$694.const$4.varHandle(MemoryLayout.PathElement.groupElement("advancedBlendNonPremultipliedDstColor"));
    static final VarHandle const$5 = constants$694.const$4.varHandle(MemoryLayout.PathElement.groupElement("advancedBlendCorrelatedOverlap"));
}


