// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1121() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "glPixelTransferf",
        constants$1082.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glPixelTransferi",
        constants$1083.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glPixelZoom",
        constants$1099.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "glPointSize",
        constants$1085.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glPolygonMode",
        constants$1083.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glPolygonOffset",
        constants$1099.const$4
    );
}


