// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$131 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$131() {}
    static final VarHandle const$0 = constants$130.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$130.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$130.const$5.varHandle(MemoryLayout.PathElement.groupElement("commandPool"));
    static final VarHandle const$3 = constants$130.const$5.varHandle(MemoryLayout.PathElement.groupElement("level"));
    static final VarHandle const$4 = constants$130.const$5.varHandle(MemoryLayout.PathElement.groupElement("commandBufferCount"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        RuntimeHelper.POINTER.withName("renderPass"),
        JAVA_INT.withName("subpass"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("framebuffer"),
        JAVA_INT.withName("occlusionQueryEnable"),
        JAVA_INT.withName("queryFlags"),
        JAVA_INT.withName("pipelineStatistics"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkCommandBufferInheritanceInfo");
}


