// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$914 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$914() {}
    static final VarHandle const$0 = constants$913.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$913.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$913.const$5.varHandle(MemoryLayout.PathElement.groupElement("reportAddressBinding"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("flags"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("baseAddress"),
        JAVA_LONG.withName("size"),
        JAVA_INT.withName("bindingType"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkDeviceAddressBindingCallbackDataEXT");
    static final VarHandle const$4 = constants$914.const$3.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$5 = constants$914.const$3.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
}


