// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$457 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$457() {}
    static final VarHandle const$0 = constants$456.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$456.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$456.const$5.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$3 = constants$456.const$5.varHandle(MemoryLayout.PathElement.groupElement("minBitstreamBufferOffsetAlignment"));
    static final VarHandle const$4 = constants$456.const$5.varHandle(MemoryLayout.PathElement.groupElement("minBitstreamBufferSizeAlignment"));
    static final VarHandle const$5 = constants$456.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxDpbSlots"));
}


