// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$754 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$754() {}
    static final VarHandle const$0 = constants$753.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$753.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$753.const$5.varHandle(MemoryLayout.PathElement.groupElement("vertexAttributeInstanceRateDivisor"));
    static final VarHandle const$3 = constants$753.const$5.varHandle(MemoryLayout.PathElement.groupElement("vertexAttributeInstanceRateZeroDivisor"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("computeDerivativeGroupQuads"),
        JAVA_INT.withName("computeDerivativeGroupLinear")
    ).withName("VkPhysicalDeviceComputeShaderDerivativesFeaturesNV");
    static final VarHandle const$5 = constants$754.const$4.varHandle(MemoryLayout.PathElement.groupElement("sType"));
}


