// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1129() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "glRecti",
        constants$1091.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glRectiv",
        constants$14.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glRects",
        constants$1091.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "glRectsv",
        constants$14.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glRenderMode",
        constants$1102.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glRotated",
        constants$1090.const$1
    );
}


