// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$200 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$200() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkCmdSetEvent",
        constants$174.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCmdResetEvent",
        constants$174.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkCmdWaitEvents",
        constants$175.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkCmdPipelineBarrier",
        constants$175.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkCmdBeginQuery",
        constants$176.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCmdEndQuery",
        constants$174.const$2
    );
}


