// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$740 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$740() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkCmdWriteAccelerationStructuresPropertiesNV",
        constants$737.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCompileDeferredNV",
        constants$158.const$5
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("representativeFragmentTest"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV");
    static final VarHandle const$3 = constants$740.const$2.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$4 = constants$740.const$2.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$5 = constants$740.const$2.varHandle(MemoryLayout.PathElement.groupElement("representativeFragmentTest"));
}


