// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1049 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1049() {}
    static final VarHandle const$0 = constants$1048.const$0.varHandle(MemoryLayout.PathElement.groupElement("maxPerStageDescriptorAccelerationStructures"));
    static final VarHandle const$1 = constants$1048.const$0.varHandle(MemoryLayout.PathElement.groupElement("maxPerStageDescriptorUpdateAfterBindAccelerationStructures"));
    static final VarHandle const$2 = constants$1048.const$0.varHandle(MemoryLayout.PathElement.groupElement("maxDescriptorSetAccelerationStructures"));
    static final VarHandle const$3 = constants$1048.const$0.varHandle(MemoryLayout.PathElement.groupElement("maxDescriptorSetUpdateAfterBindAccelerationStructures"));
    static final VarHandle const$4 = constants$1048.const$0.varHandle(MemoryLayout.PathElement.groupElement("minAccelerationStructureScratchOffsetAlignment"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        RuntimeHelper.POINTER.withName("accelerationStructure")
    ).withName("VkAccelerationStructureDeviceAddressInfoKHR");
}


