// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1077 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1077() {}
    static final VarHandle const$0 = constants$1075.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxTaskPayloadAndSharedMemorySize"));
    static final VarHandle const$1 = constants$1075.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxMeshWorkGroupTotalCount"));
    static final VarHandle const$2 = constants$1075.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxMeshWorkGroupInvocations"));
    static final VarHandle const$3 = constants$1075.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxMeshSharedMemorySize"));
    static final VarHandle const$4 = constants$1075.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxMeshPayloadAndSharedMemorySize"));
    static final VarHandle const$5 = constants$1075.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxMeshOutputMemorySize"));
}


