// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final VarHandle const$0 = constants$81.const$5.varHandle(MemoryLayout.PathElement.groupElement("mapEntryCount"));
    static final VarHandle const$1 = constants$81.const$5.varHandle(MemoryLayout.PathElement.groupElement("pMapEntries"));
    static final VarHandle const$2 = constants$81.const$5.varHandle(MemoryLayout.PathElement.groupElement("dataSize"));
    static final VarHandle const$3 = constants$81.const$5.varHandle(MemoryLayout.PathElement.groupElement("pData"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("stage"),
        RuntimeHelper.POINTER.withName("module"),
        RuntimeHelper.POINTER.withName("pName"),
        RuntimeHelper.POINTER.withName("pSpecializationInfo")
    ).withName("VkPipelineShaderStageCreateInfo");
    static final VarHandle const$5 = constants$82.const$4.varHandle(MemoryLayout.PathElement.groupElement("sType"));
}


