// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$616 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$616() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("objectType"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("object"),
        RuntimeHelper.POINTER.withName("pObjectName")
    ).withName("VkDebugMarkerObjectNameInfoEXT");
    static final VarHandle const$1 = constants$616.const$0.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$2 = constants$616.const$0.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$3 = constants$616.const$0.varHandle(MemoryLayout.PathElement.groupElement("objectType"));
    static final VarHandle const$4 = constants$616.const$0.varHandle(MemoryLayout.PathElement.groupElement("object"));
    static final VarHandle const$5 = constants$616.const$0.varHandle(MemoryLayout.PathElement.groupElement("pObjectName"));
}


