// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1107() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "glGetTexGenfv",
        constants$1084.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glGetTexGeniv",
        constants$1084.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glGetTexImage",
        constants$1097.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "glGetTexLevelParameterfv",
        constants$1093.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glGetTexLevelParameteriv",
        constants$1093.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glGetTexParameterfv",
        constants$1084.const$1
    );
}


