// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$425 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$425() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkCmdEndRendering",
        constants$0.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "vkCmdSetCullMode",
        constants$178.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkCmdSetFrontFace",
        constants$178.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkCmdSetPrimitiveTopology",
        constants$178.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkCmdSetViewportWithCount",
        constants$140.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCmdSetScissorWithCount",
        constants$140.const$5
    );
}


