// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$356 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$356() {}
    static final VarHandle const$0 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProductAccumulatingSaturating16BitUnsignedAccelerated"));
    static final VarHandle const$1 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProductAccumulatingSaturating16BitSignedAccelerated"));
    static final VarHandle const$2 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated"));
    static final VarHandle const$3 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProductAccumulatingSaturating32BitUnsignedAccelerated"));
    static final VarHandle const$4 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProductAccumulatingSaturating32BitSignedAccelerated"));
    static final VarHandle const$5 = constants$350.const$2.varHandle(MemoryLayout.PathElement.groupElement("integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated"));
}


