// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final VarHandle const$0 = constants$107.const$2.varHandle(MemoryLayout.PathElement.groupElement("setLayoutCount"));
    static final VarHandle const$1 = constants$107.const$2.varHandle(MemoryLayout.PathElement.groupElement("pSetLayouts"));
    static final VarHandle const$2 = constants$107.const$2.varHandle(MemoryLayout.PathElement.groupElement("pushConstantRangeCount"));
    static final VarHandle const$3 = constants$107.const$2.varHandle(MemoryLayout.PathElement.groupElement("pPushConstantRanges"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("magFilter"),
        JAVA_INT.withName("minFilter"),
        JAVA_INT.withName("mipmapMode"),
        JAVA_INT.withName("addressModeU"),
        JAVA_INT.withName("addressModeV"),
        JAVA_INT.withName("addressModeW"),
        JAVA_FLOAT.withName("mipLodBias"),
        JAVA_INT.withName("anisotropyEnable"),
        JAVA_FLOAT.withName("maxAnisotropy"),
        JAVA_INT.withName("compareEnable"),
        JAVA_INT.withName("compareOp"),
        JAVA_FLOAT.withName("minLod"),
        JAVA_FLOAT.withName("maxLod"),
        JAVA_INT.withName("borderColor"),
        JAVA_INT.withName("unnormalizedCoordinates")
    ).withName("VkSamplerCreateInfo");
    static final VarHandle const$5 = constants$108.const$4.varHandle(MemoryLayout.PathElement.groupElement("sType"));
}


