// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$672 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$672() {}
    static final VarHandle const$0 = constants$670.const$4.varHandle(MemoryLayout.PathElement.groupElement("degenerateTrianglesRasterized"));
    static final VarHandle const$1 = constants$670.const$4.varHandle(MemoryLayout.PathElement.groupElement("degenerateLinesRasterized"));
    static final VarHandle const$2 = constants$670.const$4.varHandle(MemoryLayout.PathElement.groupElement("fullyCoveredFragmentShaderInputVariable"));
    static final VarHandle const$3 = constants$670.const$4.varHandle(MemoryLayout.PathElement.groupElement("conservativeRasterizationPostDepthCoverage"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("conservativeRasterizationMode"),
        JAVA_FLOAT.withName("extraPrimitiveOverestimationSize"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPipelineRasterizationConservativeStateCreateInfoEXT");
    static final VarHandle const$5 = constants$672.const$4.varHandle(MemoryLayout.PathElement.groupElement("sType"));
}


