// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    static final VarHandle const$0 = constants$92.const$2.varHandle(MemoryLayout.PathElement.groupElement("depthClampEnable"));
    static final VarHandle const$1 = constants$92.const$2.varHandle(MemoryLayout.PathElement.groupElement("rasterizerDiscardEnable"));
    static final VarHandle const$2 = constants$92.const$2.varHandle(MemoryLayout.PathElement.groupElement("polygonMode"));
    static final VarHandle const$3 = constants$92.const$2.varHandle(MemoryLayout.PathElement.groupElement("cullMode"));
    static final VarHandle const$4 = constants$92.const$2.varHandle(MemoryLayout.PathElement.groupElement("frontFace"));
    static final VarHandle const$5 = constants$92.const$2.varHandle(MemoryLayout.PathElement.groupElement("depthBiasEnable"));
}


