// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$625 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$625() {}
    static final VarHandle const$0 = constants$623.const$4.varHandle(MemoryLayout.PathElement.groupElement("maxTransformFeedbackBufferDataStride"));
    static final VarHandle const$1 = constants$623.const$4.varHandle(MemoryLayout.PathElement.groupElement("transformFeedbackQueries"));
    static final VarHandle const$2 = constants$623.const$4.varHandle(MemoryLayout.PathElement.groupElement("transformFeedbackStreamsLinesTriangles"));
    static final VarHandle const$3 = constants$623.const$4.varHandle(MemoryLayout.PathElement.groupElement("transformFeedbackRasterizationStreamSelect"));
    static final VarHandle const$4 = constants$623.const$4.varHandle(MemoryLayout.PathElement.groupElement("transformFeedbackDraw"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("rasterizationStream")
    ).withName("VkPipelineRasterizationStateStreamCreateInfoEXT");
}


