// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$537 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$537() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkBindImageMemory2KHR",
        constants$147.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkGetDescriptorSetLayoutSupportKHR.class, "apply", constants$142.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkGetDescriptorSetLayoutSupportKHR",
        constants$142.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkCmdDrawIndirectCountKHR.class, "apply", constants$342.const$0);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(PFN_vkCmdDrawIndexedIndirectCountKHR.class, "apply", constants$342.const$0);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkCmdDrawIndirectCountKHR",
        constants$342.const$0
    );
}


