// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$633 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$633() {}
    static final VarHandle const$0 = constants$631.const$2.varHandle(MemoryLayout.PathElement.groupElement("sharedMemBytes"));
    static final VarHandle const$1 = constants$631.const$2.varHandle(MemoryLayout.PathElement.groupElement("paramCount"));
    static final VarHandle const$2 = constants$631.const$2.varHandle(MemoryLayout.PathElement.groupElement("pParams"));
    static final VarHandle const$3 = constants$631.const$2.varHandle(MemoryLayout.PathElement.groupElement("extraCount"));
    static final VarHandle const$4 = constants$631.const$2.varHandle(MemoryLayout.PathElement.groupElement("pExtras"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_vkCreateCuModuleNVX.class, "apply", constants$143.const$2);
}


