// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$247 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$247() {}
    static final VarHandle const$0 = constants$246.const$3.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$1 = constants$246.const$3.varHandle(MemoryLayout.PathElement.groupElement("usage"));
    static final VarHandle const$2 = constants$246.const$3.varHandle(MemoryLayout.PathElement.groupElement("handleType"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("externalMemoryFeatures"),
            JAVA_INT.withName("exportFromImportedHandleTypes"),
            JAVA_INT.withName("compatibleHandleTypes")
        ).withName("externalMemoryProperties"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkExternalBufferProperties");
    static final VarHandle const$4 = constants$247.const$3.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$5 = constants$247.const$3.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
}


