// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$591 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$591() {}
    static final VarHandle const$0 = constants$590.const$1.varHandle(MemoryLayout.PathElement.groupElement("pData"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkGetPipelineExecutablePropertiesKHR.class, "apply", constants$143.const$2);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(PFN_vkGetPipelineExecutableStatisticsKHR.class, "apply", constants$143.const$2);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkGetPipelineExecutableInternalRepresentationsKHR.class, "apply", constants$143.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkGetPipelineExecutablePropertiesKHR",
        constants$143.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "vkGetPipelineExecutableStatisticsKHR",
        constants$143.const$2
    );
}


