// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1091 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1091() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "glColor4i",
        constants$1091.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "glColor4iv",
        constants$0.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_SHORT,
        JAVA_SHORT,
        JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "glColor4s",
        constants$1091.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "glColor4sv",
        constants$0.const$0
    );
}


