// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$513 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$513() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("swapchainCount"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pRegions")
    ).withName("VkPresentRegionsKHR");
    static final VarHandle const$1 = constants$513.const$0.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$2 = constants$513.const$0.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$3 = constants$513.const$0.varHandle(MemoryLayout.PathElement.groupElement("swapchainCount"));
    static final VarHandle const$4 = constants$513.const$0.varHandle(MemoryLayout.PathElement.groupElement("pRegions"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_vkCreateDescriptorUpdateTemplateKHR.class, "apply", constants$143.const$2);
}


