// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$626 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$626() {}
    static final VarHandle const$0 = constants$625.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$625.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$625.const$5.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$3 = constants$625.const$5.varHandle(MemoryLayout.PathElement.groupElement("rasterizationStream"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_vkCmdBindTransformFeedbackBuffersEXT.class, "apply", constants$626.const$4);
}


