// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$569 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$569() {}
    static final VarHandle const$0 = constants$568.const$5.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$1 = constants$568.const$5.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$2 = constants$568.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxStdVPSCount"));
    static final VarHandle const$3 = constants$568.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxStdSPSCount"));
    static final VarHandle const$4 = constants$568.const$5.varHandle(MemoryLayout.PathElement.groupElement("maxStdPPSCount"));
    static final VarHandle const$5 = constants$568.const$5.varHandle(MemoryLayout.PathElement.groupElement("pParametersAddInfo"));
}


