// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final VarHandle const$0 = constants$16.const$0.varHandle(MemoryLayout.PathElement.groupElement("pfnInternalFree"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        RuntimeHelper.POINTER.withName("pApplicationName"),
        JAVA_INT.withName("applicationVersion"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pEngineName"),
        JAVA_INT.withName("engineVersion"),
        JAVA_INT.withName("apiVersion")
    ).withName("VkApplicationInfo");
    static final VarHandle const$2 = constants$17.const$1.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$3 = constants$17.const$1.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$4 = constants$17.const$1.varHandle(MemoryLayout.PathElement.groupElement("pApplicationName"));
    static final VarHandle const$5 = constants$17.const$1.varHandle(MemoryLayout.PathElement.groupElement("applicationVersion"));
}


