// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$159 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$159() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PFN_vkResetDescriptorPool.class, "apply", constants$158.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$158.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(PFN_vkAllocateDescriptorSets.class, "apply", constants$139.const$5);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PFN_vkFreeDescriptorSets.class, "apply", constants$156.const$1);
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_vkUpdateDescriptorSets.class, "apply", constants$159.const$4);
}


