// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$504 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$504() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "vkGetPhysicalDeviceExternalBufferPropertiesKHR",
        constants$142.const$0
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("handleType"),
        JAVA_INT.withName("fd")
    ).withName("VkImportMemoryFdInfoKHR");
    static final VarHandle const$2 = constants$504.const$1.varHandle(MemoryLayout.PathElement.groupElement("sType"));
    static final VarHandle const$3 = constants$504.const$1.varHandle(MemoryLayout.PathElement.groupElement("pNext"));
    static final VarHandle const$4 = constants$504.const$1.varHandle(MemoryLayout.PathElement.groupElement("handleType"));
    static final VarHandle const$5 = constants$504.const$1.varHandle(MemoryLayout.PathElement.groupElement("fd"));
}


