// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$611 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$611() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PFN_vkGetDeviceImageMemoryRequirementsKHR.class, "apply", constants$142.const$0);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PFN_vkGetDeviceImageSparseMemoryRequirementsKHR.class, "apply", constants$149.const$3);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vkGetDeviceBufferMemoryRequirementsKHR",
        constants$142.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "vkGetDeviceImageMemoryRequirementsKHR",
        constants$142.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "vkGetDeviceImageSparseMemoryRequirementsKHR",
        constants$149.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pNext"),
        JAVA_INT.withName("rayTracingPositionFetch"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkPhysicalDeviceRayTracingPositionFetchFeaturesKHR");
}


