// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1150() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$1149.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(GLFWreallocatefun.class, "apply", constants$1150.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$1150.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(GLFWdeallocatefun.class, "apply", constants$14.const$0);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(GLFWerrorfun.class, "apply", constants$1086.const$0);
}


