// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*GLFWerrorfun)(int error_code,char* description);
 * }
 */
public interface GLFWerrorfun {

    void apply(int error_code, java.lang.foreign.MemorySegment description);
    static MemorySegment allocate(GLFWerrorfun fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$1150.const$5, fi, constants$1086.const$0, scope);
    }
    static GLFWerrorfun ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _error_code, java.lang.foreign.MemorySegment _description) -> {
            try {
                constants$1147.const$2.invokeExact(symbol, _error_code, _description);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


