// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkCmdPushDescriptorSetKHR)(struct VkCommandBuffer_T* commandBuffer,enum VkPipelineBindPoint pipelineBindPoint,struct VkPipelineLayout_T* layout,unsigned int set,unsigned int descriptorWriteCount,struct VkWriteDescriptorSet* pDescriptorWrites);
 * }
 */
public interface PFN_vkCmdPushDescriptorSetKHR {

    void apply(java.lang.foreign.MemorySegment commandBuffer, int pipelineBindPoint, java.lang.foreign.MemorySegment layout, int set, int descriptorWriteCount, java.lang.foreign.MemorySegment pDescriptorWrites);
    static MemorySegment allocate(PFN_vkCmdPushDescriptorSetKHR fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$511.const$2, fi, constants$511.const$1, scope);
    }
    static PFN_vkCmdPushDescriptorSetKHR ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _commandBuffer, int _pipelineBindPoint, java.lang.foreign.MemorySegment _layout, int _set, int _descriptorWriteCount, java.lang.foreign.MemorySegment _pDescriptorWrites) -> {
            try {
                constants$511.const$3.invokeExact(symbol, _commandBuffer, _pipelineBindPoint, _layout, _set, _descriptorWriteCount, _pDescriptorWrites);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


