// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * enum VkResult (*PFN_vkGetSwapchainCounterEXT)(struct VkDevice_T* device,struct VkSwapchainKHR_T* swapchain,enum VkSurfaceCounterFlagBitsEXT counter,unsigned long long* pCounterValue);
 * }
 */
public interface PFN_vkGetSwapchainCounterEXT {

    int apply(java.lang.foreign.MemorySegment device, java.lang.foreign.MemorySegment swapchain, int counter, java.lang.foreign.MemorySegment pCounterValue);
    static MemorySegment allocate(PFN_vkGetSwapchainCounterEXT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$661.const$1, fi, constants$156.const$1, scope);
    }
    static PFN_vkGetSwapchainCounterEXT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _device, java.lang.foreign.MemorySegment _swapchain, int _counter, java.lang.foreign.MemorySegment _pCounterValue) -> {
            try {
                return (int)constants$156.const$3.invokeExact(symbol, _device, _swapchain, _counter, _pCounterValue);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


