// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkSetDeviceMemoryPriorityEXT)(struct VkDevice_T* device,struct VkDeviceMemory_T* memory,float priority);
 * }
 */
public interface PFN_vkSetDeviceMemoryPriorityEXT {

    void apply(java.lang.foreign.MemorySegment device, java.lang.foreign.MemorySegment memory, float priority);
    static MemorySegment allocate(PFN_vkSetDeviceMemoryPriorityEXT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$963.const$2, fi, constants$963.const$1, scope);
    }
    static PFN_vkSetDeviceMemoryPriorityEXT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _device, java.lang.foreign.MemorySegment _memory, float _priority) -> {
            try {
                constants$963.const$3.invokeExact(symbol, _device, _memory, _priority);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


