// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkGetDescriptorSetLayoutBindingOffsetEXT)(struct VkDevice_T* device,struct VkDescriptorSetLayout_T* layout,unsigned int binding,unsigned long long* pOffset);
 * }
 */
public interface PFN_vkGetDescriptorSetLayoutBindingOffsetEXT {

    void apply(java.lang.foreign.MemorySegment device, java.lang.foreign.MemorySegment layout, int binding, java.lang.foreign.MemorySegment pOffset);
    static MemorySegment allocate(PFN_vkGetDescriptorSetLayoutBindingOffsetEXT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$874.const$0, fi, constants$161.const$4, scope);
    }
    static PFN_vkGetDescriptorSetLayoutBindingOffsetEXT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _device, java.lang.foreign.MemorySegment _layout, int _binding, java.lang.foreign.MemorySegment _pOffset) -> {
            try {
                constants$162.const$0.invokeExact(symbol, _device, _layout, _binding, _pOffset);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


