// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * enum VkResult (*PFN_vkSetPrivateDataEXT)(struct VkDevice_T* device,enum VkObjectType objectType,unsigned long long objectHandle,struct VkPrivateDataSlot_T* privateDataSlot,unsigned long long data);
 * }
 */
public interface PFN_vkSetPrivateDataEXT {

    int apply(java.lang.foreign.MemorySegment device, int objectType, long objectHandle, java.lang.foreign.MemorySegment privateDataSlot, long data);
    static MemorySegment allocate(PFN_vkSetPrivateDataEXT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$853.const$5, fi, constants$414.const$4, scope);
    }
    static PFN_vkSetPrivateDataEXT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _device, int _objectType, long _objectHandle, java.lang.foreign.MemorySegment _privateDataSlot, long _data) -> {
            try {
                return (int)constants$415.const$0.invokeExact(symbol, _device, _objectType, _objectHandle, _privateDataSlot, _data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


