// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkCmdDrawMeshTasksIndirectNV)(struct VkCommandBuffer_T* commandBuffer,struct VkBuffer_T* buffer,unsigned long long offset,unsigned int drawCount,unsigned int stride);
 * }
 */
public interface PFN_vkCmdDrawMeshTasksIndirectNV {

    void apply(java.lang.foreign.MemorySegment commandBuffer, java.lang.foreign.MemorySegment buffer, long offset, int drawCount, int stride);
    static MemorySegment allocate(PFN_vkCmdDrawMeshTasksIndirectNV fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$759.const$2, fi, constants$168.const$3, scope);
    }
    static PFN_vkCmdDrawMeshTasksIndirectNV ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _commandBuffer, java.lang.foreign.MemorySegment _buffer, long _offset, int _drawCount, int _stride) -> {
            try {
                constants$168.const$5.invokeExact(symbol, _commandBuffer, _buffer, _offset, _drawCount, _stride);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


