// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkCmdUpdateBuffer)(struct VkCommandBuffer_T* commandBuffer,struct VkBuffer_T* dstBuffer,unsigned long long dstOffset,unsigned long long dataSize,void* pData);
 * }
 */
public interface PFN_vkCmdUpdateBuffer {

    void apply(java.lang.foreign.MemorySegment commandBuffer, java.lang.foreign.MemorySegment dstBuffer, long dstOffset, long dataSize, java.lang.foreign.MemorySegment pData);
    static MemorySegment allocate(PFN_vkCmdUpdateBuffer fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$172.const$5, fi, constants$172.const$4, scope);
    }
    static PFN_vkCmdUpdateBuffer ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _commandBuffer, java.lang.foreign.MemorySegment _dstBuffer, long _dstOffset, long _dataSize, java.lang.foreign.MemorySegment _pData) -> {
            try {
                constants$173.const$0.invokeExact(symbol, _commandBuffer, _dstBuffer, _dstOffset, _dataSize, _pData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


