// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkCmdSetProvokingVertexModeEXT)(struct VkCommandBuffer_T* commandBuffer,enum VkProvokingVertexModeEXT provokingVertexMode);
 * }
 */
public interface PFN_vkCmdSetProvokingVertexModeEXT {

    void apply(java.lang.foreign.MemorySegment commandBuffer, int provokingVertexMode);
    static MemorySegment allocate(PFN_vkCmdSetProvokingVertexModeEXT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$994.const$5, fi, constants$178.const$3, scope);
    }
    static PFN_vkCmdSetProvokingVertexModeEXT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _commandBuffer, int _provokingVertexMode) -> {
            try {
                constants$178.const$5.invokeExact(symbol, _commandBuffer, _provokingVertexMode);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


