// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFN_vkCmdSetConservativeRasterizationModeEXT)(struct VkCommandBuffer_T* commandBuffer,enum VkConservativeRasterizationModeEXT conservativeRasterizationMode);
 * }
 */
public interface PFN_vkCmdSetConservativeRasterizationModeEXT {

    void apply(java.lang.foreign.MemorySegment commandBuffer, int conservativeRasterizationMode);
    static MemorySegment allocate(PFN_vkCmdSetConservativeRasterizationModeEXT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$994.const$0, fi, constants$178.const$3, scope);
    }
    static PFN_vkCmdSetConservativeRasterizationModeEXT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _commandBuffer, int _conservativeRasterizationMode) -> {
            try {
                constants$178.const$5.invokeExact(symbol, _commandBuffer, _conservativeRasterizationMode);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


