// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PFNGLGETPOINTERVEXTPROC)(unsigned int pname,void** params);
 * }
 */
public interface PFNGLGETPOINTERVEXTPROC {

    void apply(int pname, java.lang.foreign.MemorySegment params);
    static MemorySegment allocate(PFNGLGETPOINTERVEXTPROC fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$1147.const$1, fi, constants$1086.const$0, scope);
    }
    static PFNGLGETPOINTERVEXTPROC ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _pname, java.lang.foreign.MemorySegment _params) -> {
            try {
                constants$1147.const$2.invokeExact(symbol, _pname, _params);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


