// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct StdVideoH264PpsFlags {
 *      *     uint32_t transform_8x8_mode_flag;
 *     uint32_t redundant_pic_cnt_present_flag;
 *     uint32_t constrained_intra_pred_flag;
 *     uint32_t deblocking_filter_control_present_flag;
 *     uint32_t weighted_pred_flag;
 *     uint32_t bottom_field_pic_order_in_frame_present_flag;
 *     uint32_t entropy_coding_mode_flag;
 *     uint32_t pic_scaling_matrix_present_flag;
 * };
 * }
 */
public class StdVideoH264PpsFlags {

    public static MemoryLayout $LAYOUT() {
        return constants$486.const$2;
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


