// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct StdVideoH265PredictorPaletteEntries {
 *     uint16_t  PredictorPaletteEntries[3][128];
 * };
 * }
 */
public class StdVideoH265PredictorPaletteEntries {

    public static MemoryLayout $LAYOUT() {
        return constants$549.const$1;
    }
    public static MemorySegment PredictorPaletteEntries$slice(MemorySegment seg) {
        return seg.asSlice(0, 768);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


