// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkAccelerationStructureTrianglesOpacityMicromapEXT {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkIndexType indexType;
 *     VkDeviceOrHostAddressConstKHR indexBuffer;
 *     VkDeviceSize indexStride;
 *     uint32_t baseTriangle;
 *     uint32_t usageCountsCount;
 *     const VkMicromapUsageEXT* pUsageCounts;
 *     const VkMicromapUsageEXT** ppUsageCounts;
 *     VkMicromapEXT micromap;
 * };
 * }
 */
public class VkAccelerationStructureTrianglesOpacityMicromapEXT {

    public static MemoryLayout $LAYOUT() {
        return constants$951.const$2;
    }
    public static VarHandle sType$VH() {
        return constants$951.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$951.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$951.const$3.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$951.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$951.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$951.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$951.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$951.const$4.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$951.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$951.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle indexType$VH() {
        return constants$951.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkIndexType indexType;
     * }
     */
    public static int indexType$get(MemorySegment seg) {
        return (int)constants$951.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkIndexType indexType;
     * }
     */
    public static void indexType$set(MemorySegment seg, int x) {
        constants$951.const$5.set(seg, x);
    }
    public static int indexType$get(MemorySegment seg, long index) {
        return (int)constants$951.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void indexType$set(MemorySegment seg, long index, int x) {
        constants$951.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment indexBuffer$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static VarHandle indexStride$VH() {
        return constants$952.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkDeviceSize indexStride;
     * }
     */
    public static long indexStride$get(MemorySegment seg) {
        return (long)constants$952.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkDeviceSize indexStride;
     * }
     */
    public static void indexStride$set(MemorySegment seg, long x) {
        constants$952.const$0.set(seg, x);
    }
    public static long indexStride$get(MemorySegment seg, long index) {
        return (long)constants$952.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void indexStride$set(MemorySegment seg, long index, long x) {
        constants$952.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle baseTriangle$VH() {
        return constants$952.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t baseTriangle;
     * }
     */
    public static int baseTriangle$get(MemorySegment seg) {
        return (int)constants$952.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t baseTriangle;
     * }
     */
    public static void baseTriangle$set(MemorySegment seg, int x) {
        constants$952.const$1.set(seg, x);
    }
    public static int baseTriangle$get(MemorySegment seg, long index) {
        return (int)constants$952.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void baseTriangle$set(MemorySegment seg, long index, int x) {
        constants$952.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle usageCountsCount$VH() {
        return constants$952.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t usageCountsCount;
     * }
     */
    public static int usageCountsCount$get(MemorySegment seg) {
        return (int)constants$952.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t usageCountsCount;
     * }
     */
    public static void usageCountsCount$set(MemorySegment seg, int x) {
        constants$952.const$2.set(seg, x);
    }
    public static int usageCountsCount$get(MemorySegment seg, long index) {
        return (int)constants$952.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void usageCountsCount$set(MemorySegment seg, long index, int x) {
        constants$952.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pUsageCounts$VH() {
        return constants$952.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const VkMicromapUsageEXT* pUsageCounts;
     * }
     */
    public static MemorySegment pUsageCounts$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$952.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const VkMicromapUsageEXT* pUsageCounts;
     * }
     */
    public static void pUsageCounts$set(MemorySegment seg, MemorySegment x) {
        constants$952.const$3.set(seg, x);
    }
    public static MemorySegment pUsageCounts$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$952.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void pUsageCounts$set(MemorySegment seg, long index, MemorySegment x) {
        constants$952.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ppUsageCounts$VH() {
        return constants$952.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const VkMicromapUsageEXT** ppUsageCounts;
     * }
     */
    public static MemorySegment ppUsageCounts$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$952.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const VkMicromapUsageEXT** ppUsageCounts;
     * }
     */
    public static void ppUsageCounts$set(MemorySegment seg, MemorySegment x) {
        constants$952.const$4.set(seg, x);
    }
    public static MemorySegment ppUsageCounts$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$952.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void ppUsageCounts$set(MemorySegment seg, long index, MemorySegment x) {
        constants$952.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle micromap$VH() {
        return constants$952.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkMicromapEXT micromap;
     * }
     */
    public static MemorySegment micromap$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$952.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkMicromapEXT micromap;
     * }
     */
    public static void micromap$set(MemorySegment seg, MemorySegment x) {
        constants$952.const$5.set(seg, x);
    }
    public static MemorySegment micromap$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$952.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void micromap$set(MemorySegment seg, long index, MemorySegment x) {
        constants$952.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


