// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct VkBufferCopy2 VkBufferCopy2KHR;
 * }
 */
public final class VkBufferCopy2KHR extends VkBufferCopy2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private VkBufferCopy2KHR() {}
}


