// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkClearDepthStencilValue {
 *     float depth;
 *     uint32_t stencil;
 * };
 * }
 */
public class VkClearDepthStencilValue {

    public static MemoryLayout $LAYOUT() {
        return constants$136.const$3;
    }
    public static VarHandle depth$VH() {
        return constants$136.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float depth;
     * }
     */
    public static float depth$get(MemorySegment seg) {
        return (float)constants$136.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float depth;
     * }
     */
    public static void depth$set(MemorySegment seg, float x) {
        constants$136.const$4.set(seg, x);
    }
    public static float depth$get(MemorySegment seg, long index) {
        return (float)constants$136.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void depth$set(MemorySegment seg, long index, float x) {
        constants$136.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle stencil$VH() {
        return constants$136.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t stencil;
     * }
     */
    public static int stencil$get(MemorySegment seg) {
        return (int)constants$136.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t stencil;
     * }
     */
    public static void stencil$set(MemorySegment seg, int x) {
        constants$136.const$5.set(seg, x);
    }
    public static int stencil$get(MemorySegment seg, long index) {
        return (int)constants$136.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void stencil$set(MemorySegment seg, long index, int x) {
        constants$136.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


