// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkCoarseSampleOrderCustomNV {
 *     VkShadingRatePaletteEntryNV shadingRate;
 *     uint32_t sampleCount;
 *     uint32_t sampleLocationCount;
 *     const VkCoarseSampleLocationNV* pSampleLocations;
 * };
 * }
 */
public class VkCoarseSampleOrderCustomNV {

    public static MemoryLayout $LAYOUT() {
        return constants$714.const$5;
    }
    public static VarHandle shadingRate$VH() {
        return constants$715.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkShadingRatePaletteEntryNV shadingRate;
     * }
     */
    public static int shadingRate$get(MemorySegment seg) {
        return (int)constants$715.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkShadingRatePaletteEntryNV shadingRate;
     * }
     */
    public static void shadingRate$set(MemorySegment seg, int x) {
        constants$715.const$0.set(seg, x);
    }
    public static int shadingRate$get(MemorySegment seg, long index) {
        return (int)constants$715.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void shadingRate$set(MemorySegment seg, long index, int x) {
        constants$715.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sampleCount$VH() {
        return constants$715.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t sampleCount;
     * }
     */
    public static int sampleCount$get(MemorySegment seg) {
        return (int)constants$715.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t sampleCount;
     * }
     */
    public static void sampleCount$set(MemorySegment seg, int x) {
        constants$715.const$1.set(seg, x);
    }
    public static int sampleCount$get(MemorySegment seg, long index) {
        return (int)constants$715.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void sampleCount$set(MemorySegment seg, long index, int x) {
        constants$715.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sampleLocationCount$VH() {
        return constants$715.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t sampleLocationCount;
     * }
     */
    public static int sampleLocationCount$get(MemorySegment seg) {
        return (int)constants$715.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t sampleLocationCount;
     * }
     */
    public static void sampleLocationCount$set(MemorySegment seg, int x) {
        constants$715.const$2.set(seg, x);
    }
    public static int sampleLocationCount$get(MemorySegment seg, long index) {
        return (int)constants$715.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void sampleLocationCount$set(MemorySegment seg, long index, int x) {
        constants$715.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pSampleLocations$VH() {
        return constants$715.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const VkCoarseSampleLocationNV* pSampleLocations;
     * }
     */
    public static MemorySegment pSampleLocations$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$715.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const VkCoarseSampleLocationNV* pSampleLocations;
     * }
     */
    public static void pSampleLocations$set(MemorySegment seg, MemorySegment x) {
        constants$715.const$3.set(seg, x);
    }
    public static MemorySegment pSampleLocations$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$715.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void pSampleLocations$set(MemorySegment seg, long index, MemorySegment x) {
        constants$715.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


