// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkCooperativeMatrixPropertiesNV {
 *     VkStructureType sType;
 *     void* pNext;
 *     uint32_t MSize;
 *     uint32_t NSize;
 *     uint32_t KSize;
 *     VkComponentTypeNV AType;
 *     VkComponentTypeNV BType;
 *     VkComponentTypeNV CType;
 *     VkComponentTypeNV DType;
 *     VkScopeNV scope;
 * };
 * }
 */
public class VkCooperativeMatrixPropertiesNV {

    public static MemoryLayout $LAYOUT() {
        return constants$787.const$5;
    }
    public static VarHandle sType$VH() {
        return constants$788.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$788.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$788.const$0.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$788.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$788.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$788.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$788.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$788.const$1.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$788.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$788.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle MSize$VH() {
        return constants$788.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t MSize;
     * }
     */
    public static int MSize$get(MemorySegment seg) {
        return (int)constants$788.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t MSize;
     * }
     */
    public static void MSize$set(MemorySegment seg, int x) {
        constants$788.const$2.set(seg, x);
    }
    public static int MSize$get(MemorySegment seg, long index) {
        return (int)constants$788.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void MSize$set(MemorySegment seg, long index, int x) {
        constants$788.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle NSize$VH() {
        return constants$788.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t NSize;
     * }
     */
    public static int NSize$get(MemorySegment seg) {
        return (int)constants$788.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t NSize;
     * }
     */
    public static void NSize$set(MemorySegment seg, int x) {
        constants$788.const$3.set(seg, x);
    }
    public static int NSize$get(MemorySegment seg, long index) {
        return (int)constants$788.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void NSize$set(MemorySegment seg, long index, int x) {
        constants$788.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle KSize$VH() {
        return constants$788.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t KSize;
     * }
     */
    public static int KSize$get(MemorySegment seg) {
        return (int)constants$788.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t KSize;
     * }
     */
    public static void KSize$set(MemorySegment seg, int x) {
        constants$788.const$4.set(seg, x);
    }
    public static int KSize$get(MemorySegment seg, long index) {
        return (int)constants$788.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void KSize$set(MemorySegment seg, long index, int x) {
        constants$788.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle AType$VH() {
        return constants$788.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkComponentTypeNV AType;
     * }
     */
    public static int AType$get(MemorySegment seg) {
        return (int)constants$788.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkComponentTypeNV AType;
     * }
     */
    public static void AType$set(MemorySegment seg, int x) {
        constants$788.const$5.set(seg, x);
    }
    public static int AType$get(MemorySegment seg, long index) {
        return (int)constants$788.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void AType$set(MemorySegment seg, long index, int x) {
        constants$788.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle BType$VH() {
        return constants$789.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkComponentTypeNV BType;
     * }
     */
    public static int BType$get(MemorySegment seg) {
        return (int)constants$789.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkComponentTypeNV BType;
     * }
     */
    public static void BType$set(MemorySegment seg, int x) {
        constants$789.const$0.set(seg, x);
    }
    public static int BType$get(MemorySegment seg, long index) {
        return (int)constants$789.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void BType$set(MemorySegment seg, long index, int x) {
        constants$789.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle CType$VH() {
        return constants$789.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkComponentTypeNV CType;
     * }
     */
    public static int CType$get(MemorySegment seg) {
        return (int)constants$789.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkComponentTypeNV CType;
     * }
     */
    public static void CType$set(MemorySegment seg, int x) {
        constants$789.const$1.set(seg, x);
    }
    public static int CType$get(MemorySegment seg, long index) {
        return (int)constants$789.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void CType$set(MemorySegment seg, long index, int x) {
        constants$789.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle DType$VH() {
        return constants$789.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkComponentTypeNV DType;
     * }
     */
    public static int DType$get(MemorySegment seg) {
        return (int)constants$789.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkComponentTypeNV DType;
     * }
     */
    public static void DType$set(MemorySegment seg, int x) {
        constants$789.const$2.set(seg, x);
    }
    public static int DType$get(MemorySegment seg, long index) {
        return (int)constants$789.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void DType$set(MemorySegment seg, long index, int x) {
        constants$789.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle scope$VH() {
        return constants$789.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkScopeNV scope;
     * }
     */
    public static int scope$get(MemorySegment seg) {
        return (int)constants$789.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkScopeNV scope;
     * }
     */
    public static void scope$set(MemorySegment seg, int x) {
        constants$789.const$3.set(seg, x);
    }
    public static int scope$get(MemorySegment seg, long index) {
        return (int)constants$789.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void scope$set(MemorySegment seg, long index, int x) {
        constants$789.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


