// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkDescriptorImageInfo {
 *     VkSampler sampler;
 *     VkImageView imageView;
 *     VkImageLayout imageLayout;
 * };
 * }
 */
public class VkDescriptorImageInfo {

    public static MemoryLayout $LAYOUT() {
        return constants$114.const$1;
    }
    public static VarHandle sampler$VH() {
        return constants$114.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkSampler sampler;
     * }
     */
    public static MemorySegment sampler$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$114.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkSampler sampler;
     * }
     */
    public static void sampler$set(MemorySegment seg, MemorySegment x) {
        constants$114.const$2.set(seg, x);
    }
    public static MemorySegment sampler$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$114.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void sampler$set(MemorySegment seg, long index, MemorySegment x) {
        constants$114.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle imageView$VH() {
        return constants$114.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkImageView imageView;
     * }
     */
    public static MemorySegment imageView$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$114.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkImageView imageView;
     * }
     */
    public static void imageView$set(MemorySegment seg, MemorySegment x) {
        constants$114.const$3.set(seg, x);
    }
    public static MemorySegment imageView$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$114.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void imageView$set(MemorySegment seg, long index, MemorySegment x) {
        constants$114.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle imageLayout$VH() {
        return constants$114.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkImageLayout imageLayout;
     * }
     */
    public static int imageLayout$get(MemorySegment seg) {
        return (int)constants$114.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkImageLayout imageLayout;
     * }
     */
    public static void imageLayout$set(MemorySegment seg, int x) {
        constants$114.const$4.set(seg, x);
    }
    public static int imageLayout$get(MemorySegment seg, long index) {
        return (int)constants$114.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void imageLayout$set(MemorySegment seg, long index, int x) {
        constants$114.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


