// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * union VkDeviceOrHostAddressConstKHR {
 *     VkDeviceAddress deviceAddress;
 *     void* hostAddress;
 * };
 * }
 */
public class VkDeviceOrHostAddressConstKHR {

    public static MemoryLayout $LAYOUT() {
        return constants$883.const$5;
    }
    public static VarHandle deviceAddress$VH() {
        return constants$884.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkDeviceAddress deviceAddress;
     * }
     */
    public static long deviceAddress$get(MemorySegment seg) {
        return (long)constants$884.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkDeviceAddress deviceAddress;
     * }
     */
    public static void deviceAddress$set(MemorySegment seg, long x) {
        constants$884.const$0.set(seg, x);
    }
    public static long deviceAddress$get(MemorySegment seg, long index) {
        return (long)constants$884.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void deviceAddress$set(MemorySegment seg, long index, long x) {
        constants$884.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hostAddress$VH() {
        return constants$884.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* hostAddress;
     * }
     */
    public static MemorySegment hostAddress$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$884.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* hostAddress;
     * }
     */
    public static void hostAddress$set(MemorySegment seg, MemorySegment x) {
        constants$884.const$1.set(seg, x);
    }
    public static MemorySegment hostAddress$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$884.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void hostAddress$set(MemorySegment seg, long index, MemorySegment x) {
        constants$884.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


