// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkHdrMetadataEXT {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkXYColorEXT displayPrimaryRed;
 *     VkXYColorEXT displayPrimaryGreen;
 *     VkXYColorEXT displayPrimaryBlue;
 *     VkXYColorEXT whitePoint;
 *     float maxLuminance;
 *     float minLuminance;
 *     float maxContentLightLevel;
 *     float maxFrameAverageLightLevel;
 * };
 * }
 */
public class VkHdrMetadataEXT {

    public static MemoryLayout $LAYOUT() {
        return constants$675.const$4;
    }
    public static VarHandle sType$VH() {
        return constants$675.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$675.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$675.const$5.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$675.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$675.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$676.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$676.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$676.const$0.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$676.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$676.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment displayPrimaryRed$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment displayPrimaryGreen$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static MemorySegment displayPrimaryBlue$slice(MemorySegment seg) {
        return seg.asSlice(32, 8);
    }
    public static MemorySegment whitePoint$slice(MemorySegment seg) {
        return seg.asSlice(40, 8);
    }
    public static VarHandle maxLuminance$VH() {
        return constants$676.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxLuminance;
     * }
     */
    public static float maxLuminance$get(MemorySegment seg) {
        return (float)constants$676.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxLuminance;
     * }
     */
    public static void maxLuminance$set(MemorySegment seg, float x) {
        constants$676.const$1.set(seg, x);
    }
    public static float maxLuminance$get(MemorySegment seg, long index) {
        return (float)constants$676.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void maxLuminance$set(MemorySegment seg, long index, float x) {
        constants$676.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle minLuminance$VH() {
        return constants$676.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float minLuminance;
     * }
     */
    public static float minLuminance$get(MemorySegment seg) {
        return (float)constants$676.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float minLuminance;
     * }
     */
    public static void minLuminance$set(MemorySegment seg, float x) {
        constants$676.const$2.set(seg, x);
    }
    public static float minLuminance$get(MemorySegment seg, long index) {
        return (float)constants$676.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void minLuminance$set(MemorySegment seg, long index, float x) {
        constants$676.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxContentLightLevel$VH() {
        return constants$676.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxContentLightLevel;
     * }
     */
    public static float maxContentLightLevel$get(MemorySegment seg) {
        return (float)constants$676.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxContentLightLevel;
     * }
     */
    public static void maxContentLightLevel$set(MemorySegment seg, float x) {
        constants$676.const$3.set(seg, x);
    }
    public static float maxContentLightLevel$get(MemorySegment seg, long index) {
        return (float)constants$676.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void maxContentLightLevel$set(MemorySegment seg, long index, float x) {
        constants$676.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxFrameAverageLightLevel$VH() {
        return constants$676.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float maxFrameAverageLightLevel;
     * }
     */
    public static float maxFrameAverageLightLevel$get(MemorySegment seg) {
        return (float)constants$676.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float maxFrameAverageLightLevel;
     * }
     */
    public static void maxFrameAverageLightLevel$set(MemorySegment seg, float x) {
        constants$676.const$4.set(seg, x);
    }
    public static float maxFrameAverageLightLevel$get(MemorySegment seg, long index) {
        return (float)constants$676.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void maxFrameAverageLightLevel$set(MemorySegment seg, long index, float x) {
        constants$676.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


