// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkImageSubresourceRange {
 *     VkImageAspectFlags aspectMask;
 *     uint32_t baseMipLevel;
 *     uint32_t levelCount;
 *     uint32_t baseArrayLayer;
 *     uint32_t layerCount;
 * };
 * }
 */
public class VkImageSubresourceRange {

    public static MemoryLayout $LAYOUT() {
        return constants$9.const$1;
    }
    public static VarHandle aspectMask$VH() {
        return constants$9.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkImageAspectFlags aspectMask;
     * }
     */
    public static int aspectMask$get(MemorySegment seg) {
        return (int)constants$9.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkImageAspectFlags aspectMask;
     * }
     */
    public static void aspectMask$set(MemorySegment seg, int x) {
        constants$9.const$2.set(seg, x);
    }
    public static int aspectMask$get(MemorySegment seg, long index) {
        return (int)constants$9.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void aspectMask$set(MemorySegment seg, long index, int x) {
        constants$9.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle baseMipLevel$VH() {
        return constants$9.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t baseMipLevel;
     * }
     */
    public static int baseMipLevel$get(MemorySegment seg) {
        return (int)constants$9.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t baseMipLevel;
     * }
     */
    public static void baseMipLevel$set(MemorySegment seg, int x) {
        constants$9.const$3.set(seg, x);
    }
    public static int baseMipLevel$get(MemorySegment seg, long index) {
        return (int)constants$9.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void baseMipLevel$set(MemorySegment seg, long index, int x) {
        constants$9.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle levelCount$VH() {
        return constants$9.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t levelCount;
     * }
     */
    public static int levelCount$get(MemorySegment seg) {
        return (int)constants$9.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t levelCount;
     * }
     */
    public static void levelCount$set(MemorySegment seg, int x) {
        constants$9.const$4.set(seg, x);
    }
    public static int levelCount$get(MemorySegment seg, long index) {
        return (int)constants$9.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void levelCount$set(MemorySegment seg, long index, int x) {
        constants$9.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle baseArrayLayer$VH() {
        return constants$9.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t baseArrayLayer;
     * }
     */
    public static int baseArrayLayer$get(MemorySegment seg) {
        return (int)constants$9.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t baseArrayLayer;
     * }
     */
    public static void baseArrayLayer$set(MemorySegment seg, int x) {
        constants$9.const$5.set(seg, x);
    }
    public static int baseArrayLayer$get(MemorySegment seg, long index) {
        return (int)constants$9.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void baseArrayLayer$set(MemorySegment seg, long index, int x) {
        constants$9.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle layerCount$VH() {
        return constants$10.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t layerCount;
     * }
     */
    public static int layerCount$get(MemorySegment seg) {
        return (int)constants$10.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t layerCount;
     * }
     */
    public static void layerCount$set(MemorySegment seg, int x) {
        constants$10.const$0.set(seg, x);
    }
    public static int layerCount$get(MemorySegment seg, long index) {
        return (int)constants$10.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void layerCount$set(MemorySegment seg, long index, int x) {
        constants$10.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


