// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct VkImageResolve2 VkImageResolve2KHR;
 * }
 */
public final class VkImageResolve2KHR extends VkImageResolve2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private VkImageResolve2KHR() {}
}


