// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkLayerProperties {
 *     char layerName[256];
 *     uint32_t specVersion;
 *     uint32_t implementationVersion;
 *     char description[256];
 * };
 * }
 */
public class VkLayerProperties {

    public static MemoryLayout $LAYOUT() {
        return constants$55.const$1;
    }
    public static MemorySegment layerName$slice(MemorySegment seg) {
        return seg.asSlice(0, 256);
    }
    public static VarHandle specVersion$VH() {
        return constants$55.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t specVersion;
     * }
     */
    public static int specVersion$get(MemorySegment seg) {
        return (int)constants$55.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t specVersion;
     * }
     */
    public static void specVersion$set(MemorySegment seg, int x) {
        constants$55.const$2.set(seg, x);
    }
    public static int specVersion$get(MemorySegment seg, long index) {
        return (int)constants$55.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void specVersion$set(MemorySegment seg, long index, int x) {
        constants$55.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle implementationVersion$VH() {
        return constants$55.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t implementationVersion;
     * }
     */
    public static int implementationVersion$get(MemorySegment seg) {
        return (int)constants$55.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t implementationVersion;
     * }
     */
    public static void implementationVersion$set(MemorySegment seg, int x) {
        constants$55.const$3.set(seg, x);
    }
    public static int implementationVersion$get(MemorySegment seg, long index) {
        return (int)constants$55.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void implementationVersion$set(MemorySegment seg, long index, int x) {
        constants$55.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment description$slice(MemorySegment seg) {
        return seg.asSlice(264, 256);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


