// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct VkMemoryBarrier2 VkMemoryBarrier2KHR;
 * }
 */
public final class VkMemoryBarrier2KHR extends VkMemoryBarrier2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private VkMemoryBarrier2KHR() {}
}


