// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkMultiDrawInfoEXT {
 *     uint32_t firstVertex;
 *     uint32_t vertexCount;
 * };
 * }
 */
public class VkMultiDrawInfoEXT {

    public static MemoryLayout $LAYOUT() {
        return constants$935.const$2;
    }
    public static VarHandle firstVertex$VH() {
        return constants$935.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t firstVertex;
     * }
     */
    public static int firstVertex$get(MemorySegment seg) {
        return (int)constants$935.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t firstVertex;
     * }
     */
    public static void firstVertex$set(MemorySegment seg, int x) {
        constants$935.const$3.set(seg, x);
    }
    public static int firstVertex$get(MemorySegment seg, long index) {
        return (int)constants$935.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void firstVertex$set(MemorySegment seg, long index, int x) {
        constants$935.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle vertexCount$VH() {
        return constants$935.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t vertexCount;
     * }
     */
    public static int vertexCount$get(MemorySegment seg) {
        return (int)constants$935.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t vertexCount;
     * }
     */
    public static void vertexCount$set(MemorySegment seg, int x) {
        constants$935.const$4.set(seg, x);
    }
    public static int vertexCount$get(MemorySegment seg, long index) {
        return (int)constants$935.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void vertexCount$set(MemorySegment seg, long index, int x) {
        constants$935.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


