// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkPhysicalDeviceDescriptorIndexingFeatures {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkBool32 shaderInputAttachmentArrayDynamicIndexing;
 *     VkBool32 shaderUniformTexelBufferArrayDynamicIndexing;
 *     VkBool32 shaderStorageTexelBufferArrayDynamicIndexing;
 *     VkBool32 shaderUniformBufferArrayNonUniformIndexing;
 *     VkBool32 shaderSampledImageArrayNonUniformIndexing;
 *     VkBool32 shaderStorageBufferArrayNonUniformIndexing;
 *     VkBool32 shaderStorageImageArrayNonUniformIndexing;
 *     VkBool32 shaderInputAttachmentArrayNonUniformIndexing;
 *     VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing;
 *     VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing;
 *     VkBool32 descriptorBindingUniformBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingSampledImageUpdateAfterBind;
 *     VkBool32 descriptorBindingStorageImageUpdateAfterBind;
 *     VkBool32 descriptorBindingStorageBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind;
 *     VkBool32 descriptorBindingUpdateUnusedWhilePending;
 *     VkBool32 descriptorBindingPartiallyBound;
 *     VkBool32 descriptorBindingVariableDescriptorCount;
 *     VkBool32 runtimeDescriptorArray;
 * };
 * }
 */
public class VkPhysicalDeviceDescriptorIndexingFeatures {

    public static MemoryLayout $LAYOUT() {
        return constants$309.const$1;
    }
    public static VarHandle sType$VH() {
        return constants$309.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$309.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$309.const$2.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$309.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$309.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$309.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$309.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$309.const$3.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$309.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$309.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderInputAttachmentArrayDynamicIndexing$VH() {
        return constants$309.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderInputAttachmentArrayDynamicIndexing;
     * }
     */
    public static int shaderInputAttachmentArrayDynamicIndexing$get(MemorySegment seg) {
        return (int)constants$309.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderInputAttachmentArrayDynamicIndexing;
     * }
     */
    public static void shaderInputAttachmentArrayDynamicIndexing$set(MemorySegment seg, int x) {
        constants$309.const$4.set(seg, x);
    }
    public static int shaderInputAttachmentArrayDynamicIndexing$get(MemorySegment seg, long index) {
        return (int)constants$309.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderInputAttachmentArrayDynamicIndexing$set(MemorySegment seg, long index, int x) {
        constants$309.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderUniformTexelBufferArrayDynamicIndexing$VH() {
        return constants$309.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderUniformTexelBufferArrayDynamicIndexing;
     * }
     */
    public static int shaderUniformTexelBufferArrayDynamicIndexing$get(MemorySegment seg) {
        return (int)constants$309.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderUniformTexelBufferArrayDynamicIndexing;
     * }
     */
    public static void shaderUniformTexelBufferArrayDynamicIndexing$set(MemorySegment seg, int x) {
        constants$309.const$5.set(seg, x);
    }
    public static int shaderUniformTexelBufferArrayDynamicIndexing$get(MemorySegment seg, long index) {
        return (int)constants$309.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderUniformTexelBufferArrayDynamicIndexing$set(MemorySegment seg, long index, int x) {
        constants$309.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderStorageTexelBufferArrayDynamicIndexing$VH() {
        return constants$310.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderStorageTexelBufferArrayDynamicIndexing;
     * }
     */
    public static int shaderStorageTexelBufferArrayDynamicIndexing$get(MemorySegment seg) {
        return (int)constants$310.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderStorageTexelBufferArrayDynamicIndexing;
     * }
     */
    public static void shaderStorageTexelBufferArrayDynamicIndexing$set(MemorySegment seg, int x) {
        constants$310.const$0.set(seg, x);
    }
    public static int shaderStorageTexelBufferArrayDynamicIndexing$get(MemorySegment seg, long index) {
        return (int)constants$310.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderStorageTexelBufferArrayDynamicIndexing$set(MemorySegment seg, long index, int x) {
        constants$310.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderUniformBufferArrayNonUniformIndexing$VH() {
        return constants$310.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderUniformBufferArrayNonUniformIndexing;
     * }
     */
    public static int shaderUniformBufferArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$310.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderUniformBufferArrayNonUniformIndexing;
     * }
     */
    public static void shaderUniformBufferArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$310.const$1.set(seg, x);
    }
    public static int shaderUniformBufferArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$310.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderUniformBufferArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$310.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderSampledImageArrayNonUniformIndexing$VH() {
        return constants$310.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderSampledImageArrayNonUniformIndexing;
     * }
     */
    public static int shaderSampledImageArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$310.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderSampledImageArrayNonUniformIndexing;
     * }
     */
    public static void shaderSampledImageArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$310.const$2.set(seg, x);
    }
    public static int shaderSampledImageArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$310.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderSampledImageArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$310.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderStorageBufferArrayNonUniformIndexing$VH() {
        return constants$310.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderStorageBufferArrayNonUniformIndexing;
     * }
     */
    public static int shaderStorageBufferArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$310.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderStorageBufferArrayNonUniformIndexing;
     * }
     */
    public static void shaderStorageBufferArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$310.const$3.set(seg, x);
    }
    public static int shaderStorageBufferArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$310.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderStorageBufferArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$310.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderStorageImageArrayNonUniformIndexing$VH() {
        return constants$310.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderStorageImageArrayNonUniformIndexing;
     * }
     */
    public static int shaderStorageImageArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$310.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderStorageImageArrayNonUniformIndexing;
     * }
     */
    public static void shaderStorageImageArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$310.const$4.set(seg, x);
    }
    public static int shaderStorageImageArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$310.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderStorageImageArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$310.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderInputAttachmentArrayNonUniformIndexing$VH() {
        return constants$310.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderInputAttachmentArrayNonUniformIndexing;
     * }
     */
    public static int shaderInputAttachmentArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$310.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderInputAttachmentArrayNonUniformIndexing;
     * }
     */
    public static void shaderInputAttachmentArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$310.const$5.set(seg, x);
    }
    public static int shaderInputAttachmentArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$310.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderInputAttachmentArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$310.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderUniformTexelBufferArrayNonUniformIndexing$VH() {
        return constants$311.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing;
     * }
     */
    public static int shaderUniformTexelBufferArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$311.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderUniformTexelBufferArrayNonUniformIndexing;
     * }
     */
    public static void shaderUniformTexelBufferArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$311.const$0.set(seg, x);
    }
    public static int shaderUniformTexelBufferArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$311.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderUniformTexelBufferArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$311.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderStorageTexelBufferArrayNonUniformIndexing$VH() {
        return constants$311.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing;
     * }
     */
    public static int shaderStorageTexelBufferArrayNonUniformIndexing$get(MemorySegment seg) {
        return (int)constants$311.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderStorageTexelBufferArrayNonUniformIndexing;
     * }
     */
    public static void shaderStorageTexelBufferArrayNonUniformIndexing$set(MemorySegment seg, int x) {
        constants$311.const$1.set(seg, x);
    }
    public static int shaderStorageTexelBufferArrayNonUniformIndexing$get(MemorySegment seg, long index) {
        return (int)constants$311.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderStorageTexelBufferArrayNonUniformIndexing$set(MemorySegment seg, long index, int x) {
        constants$311.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingUniformBufferUpdateAfterBind$VH() {
        return constants$311.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingUniformBufferUpdateAfterBind;
     * }
     */
    public static int descriptorBindingUniformBufferUpdateAfterBind$get(MemorySegment seg) {
        return (int)constants$311.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingUniformBufferUpdateAfterBind;
     * }
     */
    public static void descriptorBindingUniformBufferUpdateAfterBind$set(MemorySegment seg, int x) {
        constants$311.const$2.set(seg, x);
    }
    public static int descriptorBindingUniformBufferUpdateAfterBind$get(MemorySegment seg, long index) {
        return (int)constants$311.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingUniformBufferUpdateAfterBind$set(MemorySegment seg, long index, int x) {
        constants$311.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingSampledImageUpdateAfterBind$VH() {
        return constants$311.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingSampledImageUpdateAfterBind;
     * }
     */
    public static int descriptorBindingSampledImageUpdateAfterBind$get(MemorySegment seg) {
        return (int)constants$311.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingSampledImageUpdateAfterBind;
     * }
     */
    public static void descriptorBindingSampledImageUpdateAfterBind$set(MemorySegment seg, int x) {
        constants$311.const$3.set(seg, x);
    }
    public static int descriptorBindingSampledImageUpdateAfterBind$get(MemorySegment seg, long index) {
        return (int)constants$311.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingSampledImageUpdateAfterBind$set(MemorySegment seg, long index, int x) {
        constants$311.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingStorageImageUpdateAfterBind$VH() {
        return constants$311.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingStorageImageUpdateAfterBind;
     * }
     */
    public static int descriptorBindingStorageImageUpdateAfterBind$get(MemorySegment seg) {
        return (int)constants$311.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingStorageImageUpdateAfterBind;
     * }
     */
    public static void descriptorBindingStorageImageUpdateAfterBind$set(MemorySegment seg, int x) {
        constants$311.const$4.set(seg, x);
    }
    public static int descriptorBindingStorageImageUpdateAfterBind$get(MemorySegment seg, long index) {
        return (int)constants$311.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingStorageImageUpdateAfterBind$set(MemorySegment seg, long index, int x) {
        constants$311.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingStorageBufferUpdateAfterBind$VH() {
        return constants$311.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingStorageBufferUpdateAfterBind;
     * }
     */
    public static int descriptorBindingStorageBufferUpdateAfterBind$get(MemorySegment seg) {
        return (int)constants$311.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingStorageBufferUpdateAfterBind;
     * }
     */
    public static void descriptorBindingStorageBufferUpdateAfterBind$set(MemorySegment seg, int x) {
        constants$311.const$5.set(seg, x);
    }
    public static int descriptorBindingStorageBufferUpdateAfterBind$get(MemorySegment seg, long index) {
        return (int)constants$311.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingStorageBufferUpdateAfterBind$set(MemorySegment seg, long index, int x) {
        constants$311.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingUniformTexelBufferUpdateAfterBind$VH() {
        return constants$312.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind;
     * }
     */
    public static int descriptorBindingUniformTexelBufferUpdateAfterBind$get(MemorySegment seg) {
        return (int)constants$312.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingUniformTexelBufferUpdateAfterBind;
     * }
     */
    public static void descriptorBindingUniformTexelBufferUpdateAfterBind$set(MemorySegment seg, int x) {
        constants$312.const$0.set(seg, x);
    }
    public static int descriptorBindingUniformTexelBufferUpdateAfterBind$get(MemorySegment seg, long index) {
        return (int)constants$312.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingUniformTexelBufferUpdateAfterBind$set(MemorySegment seg, long index, int x) {
        constants$312.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingStorageTexelBufferUpdateAfterBind$VH() {
        return constants$312.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind;
     * }
     */
    public static int descriptorBindingStorageTexelBufferUpdateAfterBind$get(MemorySegment seg) {
        return (int)constants$312.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingStorageTexelBufferUpdateAfterBind;
     * }
     */
    public static void descriptorBindingStorageTexelBufferUpdateAfterBind$set(MemorySegment seg, int x) {
        constants$312.const$1.set(seg, x);
    }
    public static int descriptorBindingStorageTexelBufferUpdateAfterBind$get(MemorySegment seg, long index) {
        return (int)constants$312.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingStorageTexelBufferUpdateAfterBind$set(MemorySegment seg, long index, int x) {
        constants$312.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingUpdateUnusedWhilePending$VH() {
        return constants$312.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingUpdateUnusedWhilePending;
     * }
     */
    public static int descriptorBindingUpdateUnusedWhilePending$get(MemorySegment seg) {
        return (int)constants$312.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingUpdateUnusedWhilePending;
     * }
     */
    public static void descriptorBindingUpdateUnusedWhilePending$set(MemorySegment seg, int x) {
        constants$312.const$2.set(seg, x);
    }
    public static int descriptorBindingUpdateUnusedWhilePending$get(MemorySegment seg, long index) {
        return (int)constants$312.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingUpdateUnusedWhilePending$set(MemorySegment seg, long index, int x) {
        constants$312.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingPartiallyBound$VH() {
        return constants$312.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingPartiallyBound;
     * }
     */
    public static int descriptorBindingPartiallyBound$get(MemorySegment seg) {
        return (int)constants$312.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingPartiallyBound;
     * }
     */
    public static void descriptorBindingPartiallyBound$set(MemorySegment seg, int x) {
        constants$312.const$3.set(seg, x);
    }
    public static int descriptorBindingPartiallyBound$get(MemorySegment seg, long index) {
        return (int)constants$312.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingPartiallyBound$set(MemorySegment seg, long index, int x) {
        constants$312.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle descriptorBindingVariableDescriptorCount$VH() {
        return constants$312.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 descriptorBindingVariableDescriptorCount;
     * }
     */
    public static int descriptorBindingVariableDescriptorCount$get(MemorySegment seg) {
        return (int)constants$312.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 descriptorBindingVariableDescriptorCount;
     * }
     */
    public static void descriptorBindingVariableDescriptorCount$set(MemorySegment seg, int x) {
        constants$312.const$4.set(seg, x);
    }
    public static int descriptorBindingVariableDescriptorCount$get(MemorySegment seg, long index) {
        return (int)constants$312.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void descriptorBindingVariableDescriptorCount$set(MemorySegment seg, long index, int x) {
        constants$312.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle runtimeDescriptorArray$VH() {
        return constants$312.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 runtimeDescriptorArray;
     * }
     */
    public static int runtimeDescriptorArray$get(MemorySegment seg) {
        return (int)constants$312.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 runtimeDescriptorArray;
     * }
     */
    public static void runtimeDescriptorArray$set(MemorySegment seg, int x) {
        constants$312.const$5.set(seg, x);
    }
    public static int runtimeDescriptorArray$get(MemorySegment seg, long index) {
        return (int)constants$312.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void runtimeDescriptorArray$set(MemorySegment seg, long index, int x) {
        constants$312.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


