// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkPhysicalDeviceDrmPropertiesEXT {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkBool32 hasPrimary;
 *     VkBool32 hasRender;
 *     int64_t primaryMajor;
 *     int64_t primaryMinor;
 *     int64_t renderMajor;
 *     int64_t renderMinor;
 * };
 * }
 */
public class VkPhysicalDeviceDrmPropertiesEXT {

    public static MemoryLayout $LAYOUT() {
        return constants$912.const$2;
    }
    public static VarHandle sType$VH() {
        return constants$912.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$912.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$912.const$3.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$912.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$912.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$912.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$912.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$912.const$4.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$912.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$912.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hasPrimary$VH() {
        return constants$912.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 hasPrimary;
     * }
     */
    public static int hasPrimary$get(MemorySegment seg) {
        return (int)constants$912.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 hasPrimary;
     * }
     */
    public static void hasPrimary$set(MemorySegment seg, int x) {
        constants$912.const$5.set(seg, x);
    }
    public static int hasPrimary$get(MemorySegment seg, long index) {
        return (int)constants$912.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void hasPrimary$set(MemorySegment seg, long index, int x) {
        constants$912.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hasRender$VH() {
        return constants$913.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 hasRender;
     * }
     */
    public static int hasRender$get(MemorySegment seg) {
        return (int)constants$913.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 hasRender;
     * }
     */
    public static void hasRender$set(MemorySegment seg, int x) {
        constants$913.const$0.set(seg, x);
    }
    public static int hasRender$get(MemorySegment seg, long index) {
        return (int)constants$913.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void hasRender$set(MemorySegment seg, long index, int x) {
        constants$913.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle primaryMajor$VH() {
        return constants$913.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t primaryMajor;
     * }
     */
    public static long primaryMajor$get(MemorySegment seg) {
        return (long)constants$913.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t primaryMajor;
     * }
     */
    public static void primaryMajor$set(MemorySegment seg, long x) {
        constants$913.const$1.set(seg, x);
    }
    public static long primaryMajor$get(MemorySegment seg, long index) {
        return (long)constants$913.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void primaryMajor$set(MemorySegment seg, long index, long x) {
        constants$913.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle primaryMinor$VH() {
        return constants$913.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t primaryMinor;
     * }
     */
    public static long primaryMinor$get(MemorySegment seg) {
        return (long)constants$913.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t primaryMinor;
     * }
     */
    public static void primaryMinor$set(MemorySegment seg, long x) {
        constants$913.const$2.set(seg, x);
    }
    public static long primaryMinor$get(MemorySegment seg, long index) {
        return (long)constants$913.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void primaryMinor$set(MemorySegment seg, long index, long x) {
        constants$913.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle renderMajor$VH() {
        return constants$913.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t renderMajor;
     * }
     */
    public static long renderMajor$get(MemorySegment seg) {
        return (long)constants$913.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t renderMajor;
     * }
     */
    public static void renderMajor$set(MemorySegment seg, long x) {
        constants$913.const$3.set(seg, x);
    }
    public static long renderMajor$get(MemorySegment seg, long index) {
        return (long)constants$913.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void renderMajor$set(MemorySegment seg, long index, long x) {
        constants$913.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle renderMinor$VH() {
        return constants$913.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t renderMinor;
     * }
     */
    public static long renderMinor$get(MemorySegment seg) {
        return (long)constants$913.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t renderMinor;
     * }
     */
    public static void renderMinor$set(MemorySegment seg, long x) {
        constants$913.const$4.set(seg, x);
    }
    public static long renderMinor$get(MemorySegment seg, long index) {
        return (long)constants$913.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void renderMinor$set(MemorySegment seg, long index, long x) {
        constants$913.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


