// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkPhysicalDeviceSampleLocationsPropertiesEXT {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkSampleCountFlags sampleLocationSampleCounts;
 *     VkExtent2D maxSampleLocationGridSize;
 *     float sampleLocationCoordinateRange[2];
 *     uint32_t sampleLocationSubPixelBits;
 *     VkBool32 variableSampleLocations;
 * };
 * }
 */
public class VkPhysicalDeviceSampleLocationsPropertiesEXT {

    public static MemoryLayout $LAYOUT() {
        return constants$691.const$5;
    }
    public static VarHandle sType$VH() {
        return constants$692.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$692.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$692.const$0.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$692.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$692.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$692.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$692.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$692.const$1.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$692.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$692.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sampleLocationSampleCounts$VH() {
        return constants$692.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkSampleCountFlags sampleLocationSampleCounts;
     * }
     */
    public static int sampleLocationSampleCounts$get(MemorySegment seg) {
        return (int)constants$692.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkSampleCountFlags sampleLocationSampleCounts;
     * }
     */
    public static void sampleLocationSampleCounts$set(MemorySegment seg, int x) {
        constants$692.const$2.set(seg, x);
    }
    public static int sampleLocationSampleCounts$get(MemorySegment seg, long index) {
        return (int)constants$692.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void sampleLocationSampleCounts$set(MemorySegment seg, long index, int x) {
        constants$692.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment maxSampleLocationGridSize$slice(MemorySegment seg) {
        return seg.asSlice(20, 8);
    }
    public static MemorySegment sampleLocationCoordinateRange$slice(MemorySegment seg) {
        return seg.asSlice(28, 8);
    }
    public static VarHandle sampleLocationSubPixelBits$VH() {
        return constants$692.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t sampleLocationSubPixelBits;
     * }
     */
    public static int sampleLocationSubPixelBits$get(MemorySegment seg) {
        return (int)constants$692.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t sampleLocationSubPixelBits;
     * }
     */
    public static void sampleLocationSubPixelBits$set(MemorySegment seg, int x) {
        constants$692.const$3.set(seg, x);
    }
    public static int sampleLocationSubPixelBits$get(MemorySegment seg, long index) {
        return (int)constants$692.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void sampleLocationSubPixelBits$set(MemorySegment seg, long index, int x) {
        constants$692.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle variableSampleLocations$VH() {
        return constants$692.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 variableSampleLocations;
     * }
     */
    public static int variableSampleLocations$get(MemorySegment seg) {
        return (int)constants$692.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 variableSampleLocations;
     * }
     */
    public static void variableSampleLocations$set(MemorySegment seg, int x) {
        constants$692.const$4.set(seg, x);
    }
    public static int variableSampleLocations$get(MemorySegment seg, long index) {
        return (int)constants$692.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void variableSampleLocations$set(MemorySegment seg, long index, int x) {
        constants$692.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


