// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkPhysicalDeviceVulkan11Features {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkBool32 storageBuffer16BitAccess;
 *     VkBool32 uniformAndStorageBuffer16BitAccess;
 *     VkBool32 storagePushConstant16;
 *     VkBool32 storageInputOutput16;
 *     VkBool32 multiview;
 *     VkBool32 multiviewGeometryShader;
 *     VkBool32 multiviewTessellationShader;
 *     VkBool32 variablePointersStorageBuffer;
 *     VkBool32 variablePointers;
 *     VkBool32 protectedMemory;
 *     VkBool32 samplerYcbcrConversion;
 *     VkBool32 shaderDrawParameters;
 * };
 * }
 */
public class VkPhysicalDeviceVulkan11Features {

    public static MemoryLayout $LAYOUT() {
        return constants$267.const$4;
    }
    public static VarHandle sType$VH() {
        return constants$267.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$267.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$267.const$5.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$267.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$267.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$268.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$268.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$268.const$0.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$268.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$268.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle storageBuffer16BitAccess$VH() {
        return constants$268.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 storageBuffer16BitAccess;
     * }
     */
    public static int storageBuffer16BitAccess$get(MemorySegment seg) {
        return (int)constants$268.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 storageBuffer16BitAccess;
     * }
     */
    public static void storageBuffer16BitAccess$set(MemorySegment seg, int x) {
        constants$268.const$1.set(seg, x);
    }
    public static int storageBuffer16BitAccess$get(MemorySegment seg, long index) {
        return (int)constants$268.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void storageBuffer16BitAccess$set(MemorySegment seg, long index, int x) {
        constants$268.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle uniformAndStorageBuffer16BitAccess$VH() {
        return constants$268.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 uniformAndStorageBuffer16BitAccess;
     * }
     */
    public static int uniformAndStorageBuffer16BitAccess$get(MemorySegment seg) {
        return (int)constants$268.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 uniformAndStorageBuffer16BitAccess;
     * }
     */
    public static void uniformAndStorageBuffer16BitAccess$set(MemorySegment seg, int x) {
        constants$268.const$2.set(seg, x);
    }
    public static int uniformAndStorageBuffer16BitAccess$get(MemorySegment seg, long index) {
        return (int)constants$268.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void uniformAndStorageBuffer16BitAccess$set(MemorySegment seg, long index, int x) {
        constants$268.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle storagePushConstant16$VH() {
        return constants$268.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 storagePushConstant16;
     * }
     */
    public static int storagePushConstant16$get(MemorySegment seg) {
        return (int)constants$268.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 storagePushConstant16;
     * }
     */
    public static void storagePushConstant16$set(MemorySegment seg, int x) {
        constants$268.const$3.set(seg, x);
    }
    public static int storagePushConstant16$get(MemorySegment seg, long index) {
        return (int)constants$268.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void storagePushConstant16$set(MemorySegment seg, long index, int x) {
        constants$268.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle storageInputOutput16$VH() {
        return constants$268.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 storageInputOutput16;
     * }
     */
    public static int storageInputOutput16$get(MemorySegment seg) {
        return (int)constants$268.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 storageInputOutput16;
     * }
     */
    public static void storageInputOutput16$set(MemorySegment seg, int x) {
        constants$268.const$4.set(seg, x);
    }
    public static int storageInputOutput16$get(MemorySegment seg, long index) {
        return (int)constants$268.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void storageInputOutput16$set(MemorySegment seg, long index, int x) {
        constants$268.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle multiview$VH() {
        return constants$268.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 multiview;
     * }
     */
    public static int multiview$get(MemorySegment seg) {
        return (int)constants$268.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 multiview;
     * }
     */
    public static void multiview$set(MemorySegment seg, int x) {
        constants$268.const$5.set(seg, x);
    }
    public static int multiview$get(MemorySegment seg, long index) {
        return (int)constants$268.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void multiview$set(MemorySegment seg, long index, int x) {
        constants$268.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle multiviewGeometryShader$VH() {
        return constants$269.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 multiviewGeometryShader;
     * }
     */
    public static int multiviewGeometryShader$get(MemorySegment seg) {
        return (int)constants$269.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 multiviewGeometryShader;
     * }
     */
    public static void multiviewGeometryShader$set(MemorySegment seg, int x) {
        constants$269.const$0.set(seg, x);
    }
    public static int multiviewGeometryShader$get(MemorySegment seg, long index) {
        return (int)constants$269.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void multiviewGeometryShader$set(MemorySegment seg, long index, int x) {
        constants$269.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle multiviewTessellationShader$VH() {
        return constants$269.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 multiviewTessellationShader;
     * }
     */
    public static int multiviewTessellationShader$get(MemorySegment seg) {
        return (int)constants$269.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 multiviewTessellationShader;
     * }
     */
    public static void multiviewTessellationShader$set(MemorySegment seg, int x) {
        constants$269.const$1.set(seg, x);
    }
    public static int multiviewTessellationShader$get(MemorySegment seg, long index) {
        return (int)constants$269.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void multiviewTessellationShader$set(MemorySegment seg, long index, int x) {
        constants$269.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle variablePointersStorageBuffer$VH() {
        return constants$269.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 variablePointersStorageBuffer;
     * }
     */
    public static int variablePointersStorageBuffer$get(MemorySegment seg) {
        return (int)constants$269.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 variablePointersStorageBuffer;
     * }
     */
    public static void variablePointersStorageBuffer$set(MemorySegment seg, int x) {
        constants$269.const$2.set(seg, x);
    }
    public static int variablePointersStorageBuffer$get(MemorySegment seg, long index) {
        return (int)constants$269.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void variablePointersStorageBuffer$set(MemorySegment seg, long index, int x) {
        constants$269.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle variablePointers$VH() {
        return constants$269.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 variablePointers;
     * }
     */
    public static int variablePointers$get(MemorySegment seg) {
        return (int)constants$269.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 variablePointers;
     * }
     */
    public static void variablePointers$set(MemorySegment seg, int x) {
        constants$269.const$3.set(seg, x);
    }
    public static int variablePointers$get(MemorySegment seg, long index) {
        return (int)constants$269.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void variablePointers$set(MemorySegment seg, long index, int x) {
        constants$269.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle protectedMemory$VH() {
        return constants$269.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 protectedMemory;
     * }
     */
    public static int protectedMemory$get(MemorySegment seg) {
        return (int)constants$269.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 protectedMemory;
     * }
     */
    public static void protectedMemory$set(MemorySegment seg, int x) {
        constants$269.const$4.set(seg, x);
    }
    public static int protectedMemory$get(MemorySegment seg, long index) {
        return (int)constants$269.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void protectedMemory$set(MemorySegment seg, long index, int x) {
        constants$269.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle samplerYcbcrConversion$VH() {
        return constants$269.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 samplerYcbcrConversion;
     * }
     */
    public static int samplerYcbcrConversion$get(MemorySegment seg) {
        return (int)constants$269.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 samplerYcbcrConversion;
     * }
     */
    public static void samplerYcbcrConversion$set(MemorySegment seg, int x) {
        constants$269.const$5.set(seg, x);
    }
    public static int samplerYcbcrConversion$get(MemorySegment seg, long index) {
        return (int)constants$269.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void samplerYcbcrConversion$set(MemorySegment seg, long index, int x) {
        constants$269.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shaderDrawParameters$VH() {
        return constants$270.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkBool32 shaderDrawParameters;
     * }
     */
    public static int shaderDrawParameters$get(MemorySegment seg) {
        return (int)constants$270.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkBool32 shaderDrawParameters;
     * }
     */
    public static void shaderDrawParameters$set(MemorySegment seg, int x) {
        constants$270.const$0.set(seg, x);
    }
    public static int shaderDrawParameters$get(MemorySegment seg, long index) {
        return (int)constants$270.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void shaderDrawParameters$set(MemorySegment seg, long index, int x) {
        constants$270.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


