// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI {
 *     VkStructureType sType;
 *     void* pNext;
 *     uint32_t maxWorkGroupCount[3];
 *     uint32_t maxWorkGroupSize[3];
 *     uint32_t maxOutputClusterCount;
 *     VkDeviceSize indirectBufferOffsetAlignment;
 * };
 * }
 */
public class VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI {

    public static MemoryLayout $LAYOUT() {
        return constants$959.const$3;
    }
    public static VarHandle sType$VH() {
        return constants$959.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$959.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$959.const$4.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$959.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$959.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$959.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$959.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$959.const$5.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$959.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$959.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment maxWorkGroupCount$slice(MemorySegment seg) {
        return seg.asSlice(16, 12);
    }
    public static MemorySegment maxWorkGroupSize$slice(MemorySegment seg) {
        return seg.asSlice(28, 12);
    }
    public static VarHandle maxOutputClusterCount$VH() {
        return constants$960.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t maxOutputClusterCount;
     * }
     */
    public static int maxOutputClusterCount$get(MemorySegment seg) {
        return (int)constants$960.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t maxOutputClusterCount;
     * }
     */
    public static void maxOutputClusterCount$set(MemorySegment seg, int x) {
        constants$960.const$0.set(seg, x);
    }
    public static int maxOutputClusterCount$get(MemorySegment seg, long index) {
        return (int)constants$960.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void maxOutputClusterCount$set(MemorySegment seg, long index, int x) {
        constants$960.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle indirectBufferOffsetAlignment$VH() {
        return constants$960.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkDeviceSize indirectBufferOffsetAlignment;
     * }
     */
    public static long indirectBufferOffsetAlignment$get(MemorySegment seg) {
        return (long)constants$960.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkDeviceSize indirectBufferOffsetAlignment;
     * }
     */
    public static void indirectBufferOffsetAlignment$set(MemorySegment seg, long x) {
        constants$960.const$1.set(seg, x);
    }
    public static long indirectBufferOffsetAlignment$get(MemorySegment seg, long index) {
        return (long)constants$960.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void indirectBufferOffsetAlignment$set(MemorySegment seg, long index, long x) {
        constants$960.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


