// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkReleaseSwapchainImagesInfoEXT {
 *     VkStructureType sType;
 *     void* pNext;
 *     VkSwapchainKHR swapchain;
 *     uint32_t imageIndexCount;
 *     const uint32_t* pImageIndices;
 * };
 * }
 */
public class VkReleaseSwapchainImagesInfoEXT {

    public static MemoryLayout $LAYOUT() {
        return constants$820.const$5;
    }
    public static VarHandle sType$VH() {
        return constants$821.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static int sType$get(MemorySegment seg) {
        return (int)constants$821.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkStructureType sType;
     * }
     */
    public static void sType$set(MemorySegment seg, int x) {
        constants$821.const$0.set(seg, x);
    }
    public static int sType$get(MemorySegment seg, long index) {
        return (int)constants$821.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void sType$set(MemorySegment seg, long index, int x) {
        constants$821.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pNext$VH() {
        return constants$821.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static MemorySegment pNext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$821.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* pNext;
     * }
     */
    public static void pNext$set(MemorySegment seg, MemorySegment x) {
        constants$821.const$1.set(seg, x);
    }
    public static MemorySegment pNext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$821.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void pNext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$821.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle swapchain$VH() {
        return constants$821.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkSwapchainKHR swapchain;
     * }
     */
    public static MemorySegment swapchain$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$821.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkSwapchainKHR swapchain;
     * }
     */
    public static void swapchain$set(MemorySegment seg, MemorySegment x) {
        constants$821.const$2.set(seg, x);
    }
    public static MemorySegment swapchain$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$821.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void swapchain$set(MemorySegment seg, long index, MemorySegment x) {
        constants$821.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle imageIndexCount$VH() {
        return constants$821.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t imageIndexCount;
     * }
     */
    public static int imageIndexCount$get(MemorySegment seg) {
        return (int)constants$821.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t imageIndexCount;
     * }
     */
    public static void imageIndexCount$set(MemorySegment seg, int x) {
        constants$821.const$3.set(seg, x);
    }
    public static int imageIndexCount$get(MemorySegment seg, long index) {
        return (int)constants$821.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void imageIndexCount$set(MemorySegment seg, long index, int x) {
        constants$821.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pImageIndices$VH() {
        return constants$821.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const uint32_t* pImageIndices;
     * }
     */
    public static MemorySegment pImageIndices$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$821.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const uint32_t* pImageIndices;
     * }
     */
    public static void pImageIndices$set(MemorySegment seg, MemorySegment x) {
        constants$821.const$4.set(seg, x);
    }
    public static MemorySegment pImageIndices$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$821.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pImageIndices$set(MemorySegment seg, long index, MemorySegment x) {
        constants$821.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


