// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct VkResolveImageInfo2 VkResolveImageInfo2KHR;
 * }
 */
public final class VkResolveImageInfo2KHR extends VkResolveImageInfo2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private VkResolveImageInfo2KHR() {}
}


