// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct VkStridedDeviceAddressRegionKHR {
 *     VkDeviceAddress deviceAddress;
 *     VkDeviceSize stride;
 *     VkDeviceSize size;
 * };
 * }
 */
public class VkStridedDeviceAddressRegionKHR {

    public static MemoryLayout $LAYOUT() {
        return constants$1069.const$1;
    }
    public static VarHandle deviceAddress$VH() {
        return constants$1069.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkDeviceAddress deviceAddress;
     * }
     */
    public static long deviceAddress$get(MemorySegment seg) {
        return (long)constants$1069.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkDeviceAddress deviceAddress;
     * }
     */
    public static void deviceAddress$set(MemorySegment seg, long x) {
        constants$1069.const$2.set(seg, x);
    }
    public static long deviceAddress$get(MemorySegment seg, long index) {
        return (long)constants$1069.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void deviceAddress$set(MemorySegment seg, long index, long x) {
        constants$1069.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle stride$VH() {
        return constants$1069.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkDeviceSize stride;
     * }
     */
    public static long stride$get(MemorySegment seg) {
        return (long)constants$1069.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkDeviceSize stride;
     * }
     */
    public static void stride$set(MemorySegment seg, long x) {
        constants$1069.const$3.set(seg, x);
    }
    public static long stride$get(MemorySegment seg, long index) {
        return (long)constants$1069.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void stride$set(MemorySegment seg, long index, long x) {
        constants$1069.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle size$VH() {
        return constants$1069.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VkDeviceSize size;
     * }
     */
    public static long size$get(MemorySegment seg) {
        return (long)constants$1069.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VkDeviceSize size;
     * }
     */
    public static void size$set(MemorySegment seg, long x) {
        constants$1069.const$4.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)constants$1069.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        constants$1069.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


