// Generated by jextract

package com.icuxika.kv.jextract.glfw;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct VkSubpassDependency2 VkSubpassDependency2KHR;
 * }
 */
public final class VkSubpassDependency2KHR extends VkSubpassDependency2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private VkSubpassDependency2KHR() {}
}


