// Generated by jextract

package com.icuxika.kv.jextract.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "GetKeyNameTextA",
        constants$2.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetKeyNameTextW",
        constants$2.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetWindowsHookExA",
        constants$2.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SetWindowsHookExW",
        constants$2.const$3
    );
}


