// Generated by jextract

package com.icuxika.kv.jextract.demo;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__conio_common_vcwprintf_s",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__conio_common_vcwprintf_p",
        constants$9.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "__conio_common_vcwscanf",
        constants$9.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__pctype_func",
        constants$3.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "__pwctype_func",
        constants$3.const$5
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_SHORT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "iswalnum",
        constants$10.const$5
    );
}


