// Generated by jextract

package com.icuxika.kv.jextract.demo;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__wcserror_s",
        constants$7.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_wcsicmp",
        constants$24.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_wcsicmp_l",
        constants$34.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "_wcsnicmp",
        constants$5.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_wcsnicmp_l",
        constants$49.const$4
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_SHORT,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "_wcsnset_s",
        constants$55.const$5
    );
}


